package com.entity;

import java.util.Date;

public class Accumulation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accumulation.accumulation
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer accumulation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accumulation.lmkbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer lmkbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accumulation.grzhbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer grzhbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accumulation.netinfoId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer netinfoid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accumulation.dkxxbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer dkxxbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accumulation.UnitInfoId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer unitinfoid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accumulation.ExtractingAmount
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer extractingamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accumulation.grapprovalStatuss
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private String grapprovalstatuss;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accumulation.spsj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Date spsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accumulation.sqsj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Date sqsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accumulation.fwdz
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private String fwdz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accumulation.gfhtxybh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private String gfhtxybh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accumulation.fwmj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer fwmj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accumulation.fwdj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer fwdj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accumulation.fwzj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer fwzj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accumulation.fzzc
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer fzzc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accumulation.zfhth
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private String zfhth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accumulation.zzlwhth
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private String zzlwhth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accumulation.dkzje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer dkzje;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accumulation.txpwwh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private String txpwwh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulation.accumulation
     *
     * @return the value of accumulation.accumulation
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getAccumulation() {
        return accumulation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulation.accumulation
     *
     * @param accumulation the value for accumulation.accumulation
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setAccumulation(Integer accumulation) {
        this.accumulation = accumulation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulation.lmkbh
     *
     * @return the value of accumulation.lmkbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getLmkbh() {
        return lmkbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulation.lmkbh
     *
     * @param lmkbh the value for accumulation.lmkbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setLmkbh(Integer lmkbh) {
        this.lmkbh = lmkbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulation.grzhbh
     *
     * @return the value of accumulation.grzhbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getGrzhbh() {
        return grzhbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulation.grzhbh
     *
     * @param grzhbh the value for accumulation.grzhbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setGrzhbh(Integer grzhbh) {
        this.grzhbh = grzhbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulation.netinfoId
     *
     * @return the value of accumulation.netinfoId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getNetinfoid() {
        return netinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulation.netinfoId
     *
     * @param netinfoid the value for accumulation.netinfoId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setNetinfoid(Integer netinfoid) {
        this.netinfoid = netinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulation.dkxxbh
     *
     * @return the value of accumulation.dkxxbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getDkxxbh() {
        return dkxxbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulation.dkxxbh
     *
     * @param dkxxbh the value for accumulation.dkxxbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setDkxxbh(Integer dkxxbh) {
        this.dkxxbh = dkxxbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulation.UnitInfoId
     *
     * @return the value of accumulation.UnitInfoId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getUnitinfoid() {
        return unitinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulation.UnitInfoId
     *
     * @param unitinfoid the value for accumulation.UnitInfoId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setUnitinfoid(Integer unitinfoid) {
        this.unitinfoid = unitinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulation.ExtractingAmount
     *
     * @return the value of accumulation.ExtractingAmount
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getExtractingamount() {
        return extractingamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulation.ExtractingAmount
     *
     * @param extractingamount the value for accumulation.ExtractingAmount
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setExtractingamount(Integer extractingamount) {
        this.extractingamount = extractingamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulation.grapprovalStatuss
     *
     * @return the value of accumulation.grapprovalStatuss
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public String getGrapprovalstatuss() {
        return grapprovalstatuss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulation.grapprovalStatuss
     *
     * @param grapprovalstatuss the value for accumulation.grapprovalStatuss
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setGrapprovalstatuss(String grapprovalstatuss) {
        this.grapprovalstatuss = grapprovalstatuss == null ? null : grapprovalstatuss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulation.spsj
     *
     * @return the value of accumulation.spsj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Date getSpsj() {
        return spsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulation.spsj
     *
     * @param spsj the value for accumulation.spsj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setSpsj(Date spsj) {
        this.spsj = spsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulation.sqsj
     *
     * @return the value of accumulation.sqsj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Date getSqsj() {
        return sqsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulation.sqsj
     *
     * @param sqsj the value for accumulation.sqsj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setSqsj(Date sqsj) {
        this.sqsj = sqsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulation.fwdz
     *
     * @return the value of accumulation.fwdz
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public String getFwdz() {
        return fwdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulation.fwdz
     *
     * @param fwdz the value for accumulation.fwdz
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setFwdz(String fwdz) {
        this.fwdz = fwdz == null ? null : fwdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulation.gfhtxybh
     *
     * @return the value of accumulation.gfhtxybh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public String getGfhtxybh() {
        return gfhtxybh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulation.gfhtxybh
     *
     * @param gfhtxybh the value for accumulation.gfhtxybh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setGfhtxybh(String gfhtxybh) {
        this.gfhtxybh = gfhtxybh == null ? null : gfhtxybh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulation.fwmj
     *
     * @return the value of accumulation.fwmj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getFwmj() {
        return fwmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulation.fwmj
     *
     * @param fwmj the value for accumulation.fwmj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setFwmj(Integer fwmj) {
        this.fwmj = fwmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulation.fwdj
     *
     * @return the value of accumulation.fwdj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getFwdj() {
        return fwdj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulation.fwdj
     *
     * @param fwdj the value for accumulation.fwdj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setFwdj(Integer fwdj) {
        this.fwdj = fwdj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulation.fwzj
     *
     * @return the value of accumulation.fwzj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getFwzj() {
        return fwzj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulation.fwzj
     *
     * @param fwzj the value for accumulation.fwzj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setFwzj(Integer fwzj) {
        this.fwzj = fwzj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulation.fzzc
     *
     * @return the value of accumulation.fzzc
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getFzzc() {
        return fzzc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulation.fzzc
     *
     * @param fzzc the value for accumulation.fzzc
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setFzzc(Integer fzzc) {
        this.fzzc = fzzc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulation.zfhth
     *
     * @return the value of accumulation.zfhth
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public String getZfhth() {
        return zfhth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulation.zfhth
     *
     * @param zfhth the value for accumulation.zfhth
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setZfhth(String zfhth) {
        this.zfhth = zfhth == null ? null : zfhth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulation.zzlwhth
     *
     * @return the value of accumulation.zzlwhth
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public String getZzlwhth() {
        return zzlwhth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulation.zzlwhth
     *
     * @param zzlwhth the value for accumulation.zzlwhth
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setZzlwhth(String zzlwhth) {
        this.zzlwhth = zzlwhth == null ? null : zzlwhth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulation.dkzje
     *
     * @return the value of accumulation.dkzje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getDkzje() {
        return dkzje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulation.dkzje
     *
     * @param dkzje the value for accumulation.dkzje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setDkzje(Integer dkzje) {
        this.dkzje = dkzje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulation.txpwwh
     *
     * @return the value of accumulation.txpwwh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public String getTxpwwh() {
        return txpwwh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulation.txpwwh
     *
     * @param txpwwh the value for accumulation.txpwwh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setTxpwwh(String txpwwh) {
        this.txpwwh = txpwwh == null ? null : txpwwh.trim();
    }
}