package com.entity;

import java.util.Date;

public class Accumulation {
    private Integer accumulation;
    private Integer lmkbh;

    private Integer grzhbh;

    private Integer netinfoid;

    private Integer dkxxbh;

    private Integer unitinfoid;

    private Integer extractingamount;

    private String grapprovalstatuss;

    private Date spsj;

    private Date sqsj;

    private String fwdz;

    private String gfhtxybh;

    private Integer fwmj;

    private Integer fwdj;

    private Integer fwzj;

    private Integer fzzc;

    private String zfhth;

    private String zzlwhth;

    private Integer dkzje;

    private String txpwwh;


    private Integer tqyyid;

    public Integer getAccumulation() {
        return accumulation;
    }

    public void setAccumulation(Integer accumulation) {
        this.accumulation = accumulation;
    }

    public Integer getLmkbh() {
        return lmkbh;
    }

    public void setLmkbh(Integer lmkbh) {
        this.lmkbh = lmkbh;
    }

    public Integer getGrzhbh() {
        return grzhbh;
    }

    public void setGrzhbh(Integer grzhbh) {
        this.grzhbh = grzhbh;
    }

    public Integer getNetinfoid() {
        return netinfoid;
    }

    public void setNetinfoid(Integer netinfoid) {
        this.netinfoid = netinfoid;
    }

    public Integer getDkxxbh() {
        return dkxxbh;
    }

    public void setDkxxbh(Integer dkxxbh) {
        this.dkxxbh = dkxxbh;
    }

    public Integer getUnitinfoid() {
        return unitinfoid;
    }

    public void setUnitinfoid(Integer unitinfoid) {
        this.unitinfoid = unitinfoid;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulation.ExtractingAmount
     *
     * @return the value of accumulation.ExtractingAmount
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getExtractingamount() {
        return extractingamount;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulation.ExtractingAmount
     *
     * @param extractingamount the value for accumulation.ExtractingAmount
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setExtractingamount(Integer extractingamount) {
        this.extractingamount = extractingamount;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulation.grapprovalStatuss
     *
     * @return the value of accumulation.grapprovalStatuss
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getGrapprovalstatuss() {
        return grapprovalstatuss;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulation.grapprovalStatuss
     *
     * @param grapprovalstatuss the value for accumulation.grapprovalStatuss
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setGrapprovalstatuss(String grapprovalstatuss) {
        this.grapprovalstatuss = grapprovalstatuss == null ? null : grapprovalstatuss.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulation.spsj
     *
     * @return the value of accumulation.spsj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Date getSpsj() {
        return spsj;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulation.spsj
     *
     * @param spsj the value for accumulation.spsj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setSpsj(Date spsj) {
        this.spsj = spsj;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulation.sqsj
     *
     * @return the value of accumulation.sqsj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Date getSqsj() {
        return sqsj;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulation.sqsj
     *
     * @param sqsj the value for accumulation.sqsj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setSqsj(Date sqsj) {
        this.sqsj = sqsj;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulation.fwdz
     *
     * @return the value of accumulation.fwdz
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getFwdz() {
        return fwdz;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulation.fwdz
     *
     * @param fwdz the value for accumulation.fwdz
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setFwdz(String fwdz) {
        this.fwdz = fwdz == null ? null : fwdz.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulation.gfhtxybh
     *
     * @return the value of accumulation.gfhtxybh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getGfhtxybh() {
        return gfhtxybh;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulation.gfhtxybh
     *
     * @param gfhtxybh the value for accumulation.gfhtxybh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setGfhtxybh(String gfhtxybh) {
        this.gfhtxybh = gfhtxybh == null ? null : gfhtxybh.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulation.fwmj
     *
     * @return the value of accumulation.fwmj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getFwmj() {
        return fwmj;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulation.fwmj
     *
     * @param fwmj the value for accumulation.fwmj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setFwmj(Integer fwmj) {
        this.fwmj = fwmj;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulation.fwdj
     *
     * @return the value of accumulation.fwdj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getFwdj() {
        return fwdj;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulation.fwdj
     *
     * @param fwdj the value for accumulation.fwdj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setFwdj(Integer fwdj) {
        this.fwdj = fwdj;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulation.fwzj
     *
     * @return the value of accumulation.fwzj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getFwzj() {
        return fwzj;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulation.fwzj
     *
     * @param fwzj the value for accumulation.fwzj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setFwzj(Integer fwzj) {
        this.fwzj = fwzj;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulation.fzzc
     *
     * @return the value of accumulation.fzzc
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getFzzc() {
        return fzzc;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulation.fzzc
     *
     * @param fzzc the value for accumulation.fzzc
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setFzzc(Integer fzzc) {
        this.fzzc = fzzc;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulation.zfhth
     *
     * @return the value of accumulation.zfhth
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getZfhth() {
        return zfhth;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulation.zfhth
     *
     * @param zfhth the value for accumulation.zfhth
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setZfhth(String zfhth) {
        this.zfhth = zfhth == null ? null : zfhth.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulation.zzlwhth
     *
     * @return the value of accumulation.zzlwhth
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getZzlwhth() {
        return zzlwhth;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulation.zzlwhth
     *
     * @param zzlwhth the value for accumulation.zzlwhth
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setZzlwhth(String zzlwhth) {
        this.zzlwhth = zzlwhth == null ? null : zzlwhth.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulation.dkzje
     *
     * @return the value of accumulation.dkzje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getDkzje() {
        return dkzje;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulation.dkzje
     *
     * @param dkzje the value for accumulation.dkzje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setDkzje(Integer dkzje) {
        this.dkzje = dkzje;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumulation.txpwwh
     *
     * @return the value of accumulation.txpwwh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getTxpwwh() {
        return txpwwh;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumulation.txpwwh
     *
     * @param txpwwh the value for accumulation.txpwwh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setTxpwwh(String txpwwh) {
        this.txpwwh = txpwwh == null ? null : txpwwh.trim();
    }

    public Integer getTqyyid() {
        return tqyyid;
    }

    public void setTqyyid(Integer tqyyid) {
        this.tqyyid = tqyyid;
    }
}