package com.entity;

import java.util.Date;

public class Grzfbkzhxx {
<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grzfbkzhxx.dkbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer dkbh;
    private String name;
    private Integer dksyqs;
    

<<<<<<< HEAD

    public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getDksyqs() {
		return dksyqs;
	}

	public void setDksyqs(Integer dksyqs) {
		this.dksyqs = dksyqs;
	}

=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grzfbkzhxx.dkxxbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer dkxxbh;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grzfbkzhxx.dkzh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String dkzh;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grzfbkzhxx.dkffe
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer dkffe;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grzfbkzhxx.dkffrq
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Date dkffrq;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grzfbkzhxx.dkye
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer dkye;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grzfbkzhxx.zxll
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer zxll;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grzfbkzhxx.llfdbl
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer llfdbl;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grzfbkzhxx.grdkqs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer grdkqs;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grzfbkzhxx.dqjhhkje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer dqjhhkje;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grzfbkzhxx.grdqjhghbj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer grdqjhghbj;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grzfbkzhxx.dqjhghlxs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer dqjhghlxs;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grzfbkzhxx.dqyhze
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer dqyhze;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grzfbkzhxx.dqyhbj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer dqyhbj;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grzfbkzhxx.dqyhlx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer dqyhlx;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grzfbkzhxx.dqyhfx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer dqyhfx;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grzfbkzhxx.dkjqrq
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Date dkjqrq;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grzfbkzhxx.hsbjze
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer hsbjze;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grzfbkzhxx.hslxze
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer hslxze;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grzfbkzhxx.fxze
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer fxze;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grzfbkzhxx.tqghbjze
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer tqghbjze;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grzfbkzhxx.grfdyqbj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer grfdyqbj;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grzfbkzhxx.grfdyqlx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer grfdyqlx;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grzfbkzhxx.ljyqqs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer ljyqqs;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grzfbkzhxx.shzt
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String shzt;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grzfbkzhxx.sfzx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String sfzx;

<<<<<<< HEAD
    public Integer getDkbh() {
=======
    private String name;
    private String dksyqs;
    
 
    
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDksyqs() {
		return dksyqs;
	}

	public void setDksyqs(String dksyqs) {
		this.dksyqs = dksyqs;
	}

	public Integer getDkbh() {
>>>>>>> refs/remotes/origin/wangcc
        return dkbh;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grzfbkzhxx.dkbh
     *
     * @param dkbh the value for grzfbkzhxx.dkbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setDkbh(Integer dkbh) {
        this.dkbh = dkbh;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grzfbkzhxx.dkxxbh
     *
     * @return the value of grzfbkzhxx.dkxxbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getDkxxbh() {
        return dkxxbh;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grzfbkzhxx.dkxxbh
     *
     * @param dkxxbh the value for grzfbkzhxx.dkxxbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setDkxxbh(Integer dkxxbh) {
        this.dkxxbh = dkxxbh;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grzfbkzhxx.dkzh
     *
     * @return the value of grzfbkzhxx.dkzh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getDkzh() {
        return dkzh;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grzfbkzhxx.dkzh
     *
     * @param dkzh the value for grzfbkzhxx.dkzh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setDkzh(String dkzh) {
        this.dkzh = dkzh == null ? null : dkzh.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grzfbkzhxx.dkffe
     *
     * @return the value of grzfbkzhxx.dkffe
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getDkffe() {
        return dkffe;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grzfbkzhxx.dkffe
     *
     * @param dkffe the value for grzfbkzhxx.dkffe
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setDkffe(Integer dkffe) {
        this.dkffe = dkffe;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grzfbkzhxx.dkffrq
     *
     * @return the value of grzfbkzhxx.dkffrq
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Date getDkffrq() {
        return dkffrq;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grzfbkzhxx.dkffrq
     *
     * @param dkffrq the value for grzfbkzhxx.dkffrq
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setDkffrq(Date dkffrq) {
        this.dkffrq = dkffrq;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grzfbkzhxx.dkye
     *
     * @return the value of grzfbkzhxx.dkye
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getDkye() {
        return dkye;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grzfbkzhxx.dkye
     *
     * @param dkye the value for grzfbkzhxx.dkye
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setDkye(Integer dkye) {
        this.dkye = dkye;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grzfbkzhxx.zxll
     *
     * @return the value of grzfbkzhxx.zxll
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getZxll() {
        return zxll;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grzfbkzhxx.zxll
     *
     * @param zxll the value for grzfbkzhxx.zxll
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setZxll(Integer zxll) {
        this.zxll = zxll;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grzfbkzhxx.llfdbl
     *
     * @return the value of grzfbkzhxx.llfdbl
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getLlfdbl() {
        return llfdbl;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grzfbkzhxx.llfdbl
     *
     * @param llfdbl the value for grzfbkzhxx.llfdbl
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setLlfdbl(Integer llfdbl) {
        this.llfdbl = llfdbl;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grzfbkzhxx.grdkqs
     *
     * @return the value of grzfbkzhxx.grdkqs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getGrdkqs() {
        return grdkqs;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grzfbkzhxx.grdkqs
     *
     * @param grdkqs the value for grzfbkzhxx.grdkqs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setGrdkqs(Integer grdkqs) {
        this.grdkqs = grdkqs;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grzfbkzhxx.dqjhhkje
     *
     * @return the value of grzfbkzhxx.dqjhhkje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getDqjhhkje() {
        return dqjhhkje;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grzfbkzhxx.dqjhhkje
     *
     * @param dqjhhkje the value for grzfbkzhxx.dqjhhkje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setDqjhhkje(Integer dqjhhkje) {
        this.dqjhhkje = dqjhhkje;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grzfbkzhxx.grdqjhghbj
     *
     * @return the value of grzfbkzhxx.grdqjhghbj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getGrdqjhghbj() {
        return grdqjhghbj;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grzfbkzhxx.grdqjhghbj
     *
     * @param grdqjhghbj the value for grzfbkzhxx.grdqjhghbj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setGrdqjhghbj(Integer grdqjhghbj) {
        this.grdqjhghbj = grdqjhghbj;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grzfbkzhxx.dqjhghlxs
     *
     * @return the value of grzfbkzhxx.dqjhghlxs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getDqjhghlxs() {
        return dqjhghlxs;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grzfbkzhxx.dqjhghlxs
     *
     * @param dqjhghlxs the value for grzfbkzhxx.dqjhghlxs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setDqjhghlxs(Integer dqjhghlxs) {
        this.dqjhghlxs = dqjhghlxs;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grzfbkzhxx.dqyhze
     *
     * @return the value of grzfbkzhxx.dqyhze
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getDqyhze() {
        return dqyhze;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grzfbkzhxx.dqyhze
     *
     * @param dqyhze the value for grzfbkzhxx.dqyhze
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setDqyhze(Integer dqyhze) {
        this.dqyhze = dqyhze;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grzfbkzhxx.dqyhbj
     *
     * @return the value of grzfbkzhxx.dqyhbj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getDqyhbj() {
        return dqyhbj;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grzfbkzhxx.dqyhbj
     *
     * @param dqyhbj the value for grzfbkzhxx.dqyhbj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setDqyhbj(Integer dqyhbj) {
        this.dqyhbj = dqyhbj;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grzfbkzhxx.dqyhlx
     *
     * @return the value of grzfbkzhxx.dqyhlx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getDqyhlx() {
        return dqyhlx;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grzfbkzhxx.dqyhlx
     *
     * @param dqyhlx the value for grzfbkzhxx.dqyhlx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setDqyhlx(Integer dqyhlx) {
        this.dqyhlx = dqyhlx;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grzfbkzhxx.dqyhfx
     *
     * @return the value of grzfbkzhxx.dqyhfx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getDqyhfx() {
        return dqyhfx;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grzfbkzhxx.dqyhfx
     *
     * @param dqyhfx the value for grzfbkzhxx.dqyhfx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setDqyhfx(Integer dqyhfx) {
        this.dqyhfx = dqyhfx;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grzfbkzhxx.dkjqrq
     *
     * @return the value of grzfbkzhxx.dkjqrq
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Date getDkjqrq() {
        return dkjqrq;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grzfbkzhxx.dkjqrq
     *
     * @param dkjqrq the value for grzfbkzhxx.dkjqrq
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setDkjqrq(Date dkjqrq) {
        this.dkjqrq = dkjqrq;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grzfbkzhxx.hsbjze
     *
     * @return the value of grzfbkzhxx.hsbjze
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getHsbjze() {
        return hsbjze;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grzfbkzhxx.hsbjze
     *
     * @param hsbjze the value for grzfbkzhxx.hsbjze
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setHsbjze(Integer hsbjze) {
        this.hsbjze = hsbjze;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grzfbkzhxx.hslxze
     *
     * @return the value of grzfbkzhxx.hslxze
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getHslxze() {
        return hslxze;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grzfbkzhxx.hslxze
     *
     * @param hslxze the value for grzfbkzhxx.hslxze
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setHslxze(Integer hslxze) {
        this.hslxze = hslxze;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grzfbkzhxx.fxze
     *
     * @return the value of grzfbkzhxx.fxze
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getFxze() {
        return fxze;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grzfbkzhxx.fxze
     *
     * @param fxze the value for grzfbkzhxx.fxze
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setFxze(Integer fxze) {
        this.fxze = fxze;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grzfbkzhxx.tqghbjze
     *
     * @return the value of grzfbkzhxx.tqghbjze
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getTqghbjze() {
        return tqghbjze;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grzfbkzhxx.tqghbjze
     *
     * @param tqghbjze the value for grzfbkzhxx.tqghbjze
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setTqghbjze(Integer tqghbjze) {
        this.tqghbjze = tqghbjze;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grzfbkzhxx.grfdyqbj
     *
     * @return the value of grzfbkzhxx.grfdyqbj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getGrfdyqbj() {
        return grfdyqbj;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grzfbkzhxx.grfdyqbj
     *
     * @param grfdyqbj the value for grzfbkzhxx.grfdyqbj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setGrfdyqbj(Integer grfdyqbj) {
        this.grfdyqbj = grfdyqbj;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grzfbkzhxx.grfdyqlx
     *
     * @return the value of grzfbkzhxx.grfdyqlx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getGrfdyqlx() {
        return grfdyqlx;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grzfbkzhxx.grfdyqlx
     *
     * @param grfdyqlx the value for grzfbkzhxx.grfdyqlx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setGrfdyqlx(Integer grfdyqlx) {
        this.grfdyqlx = grfdyqlx;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grzfbkzhxx.ljyqqs
     *
     * @return the value of grzfbkzhxx.ljyqqs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getLjyqqs() {
        return ljyqqs;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grzfbkzhxx.ljyqqs
     *
     * @param ljyqqs the value for grzfbkzhxx.ljyqqs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setLjyqqs(Integer ljyqqs) {
        this.ljyqqs = ljyqqs;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grzfbkzhxx.shzt
     *
     * @return the value of grzfbkzhxx.shzt
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getShzt() {
        return shzt;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grzfbkzhxx.shzt
     *
     * @param shzt the value for grzfbkzhxx.shzt
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setShzt(String shzt) {
        this.shzt = shzt == null ? null : shzt.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grzfbkzhxx.sfzx
     *
     * @return the value of grzfbkzhxx.sfzx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getSfzx() {
        return sfzx;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grzfbkzhxx.sfzx
     *
     * @param sfzx the value for grzfbkzhxx.sfzx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setSfzx(String sfzx) {
        this.sfzx = sfzx == null ? null : sfzx.trim();
    }
}