package com.entity;

public class Gshylx {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gshylx.gshylxbh
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    private Integer gshylxbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gshylx.UnitInfoId
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    private Integer unitinfoid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gshylx.gshylxmc
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    private String gshylxmc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gshylx.gshylxbh
     *
     * @return the value of gshylx.gshylxbh
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public Integer getGshylxbh() {
        return gshylxbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gshylx.gshylxbh
     *
     * @param gshylxbh the value for gshylx.gshylxbh
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public void setGshylxbh(Integer gshylxbh) {
        this.gshylxbh = gshylxbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gshylx.UnitInfoId
     *
     * @return the value of gshylx.UnitInfoId
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public Integer getUnitinfoid() {
        return unitinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gshylx.UnitInfoId
     *
     * @param unitinfoid the value for gshylx.UnitInfoId
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public void setUnitinfoid(Integer unitinfoid) {
        this.unitinfoid = unitinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gshylx.gshylxmc
     *
     * @return the value of gshylx.gshylxmc
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public String getGshylxmc() {
        return gshylxmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gshylx.gshylxmc
     *
     * @param gshylxmc the value for gshylx.gshylxmc
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public void setGshylxmc(String gshylxmc) {
        this.gshylxmc = gshylxmc == null ? null : gshylxmc.trim();
    }
}