package com.entity;

public class Gshylx {
<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gshylx.gshylxbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer gshylxbh;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gshylx.gshylxmc
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String gshylxmc;

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gshylx.gshylxbh
     *
     * @return the value of gshylx.gshylxbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getGshylxbh() {
        return gshylxbh;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gshylx.gshylxbh
     *
     * @param gshylxbh the value for gshylx.gshylxbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setGshylxbh(Integer gshylxbh) {
        this.gshylxbh = gshylxbh;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gshylx.gshylxmc
     *
     * @return the value of gshylx.gshylxmc
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getGshylxmc() {
        return gshylxmc;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gshylx.gshylxmc
     *
     * @param gshylxmc the value for gshylx.gshylxmc
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setGshylxmc(String gshylxmc) {
        this.gshylxmc = gshylxmc == null ? null : gshylxmc.trim();
    }
}