package com.entity;

public class Gslxb {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gslxb.gslxbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer gslxbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gslxb.gslxmc
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private String gslxmc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gslxb.gslxbh
     *
     * @return the value of gslxb.gslxbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getGslxbh() {
        return gslxbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gslxb.gslxbh
     *
     * @param gslxbh the value for gslxb.gslxbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setGslxbh(Integer gslxbh) {
        this.gslxbh = gslxbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gslxb.gslxmc
     *
     * @return the value of gslxb.gslxmc
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public String getGslxmc() {
        return gslxmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gslxb.gslxmc
     *
     * @param gslxmc the value for gslxb.gslxmc
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setGslxmc(String gslxmc) {
        this.gslxmc = gslxmc == null ? null : gslxmc.trim();
    }
}