package com.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class Hjqcb {
<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hjqcb.hjbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer hjbh;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hjqcb.UnitInfoAccount
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer unitinfoaccount;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hjqcb.grzhbhs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer grzhbhs;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hjqcb.userId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer userid;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hjqcb.gjind
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String gjind;
<<<<<<< HEAD
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT-8")
=======

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hjqcb.jnmy
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Date jnmy;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hjqcb.nhyf
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer nhyf;
<<<<<<< HEAD
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT-8")
=======

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hjqcb.bjjzrq
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Date bjjzrq;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hjqcb.bczjrs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer bczjrs;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hjqcb.bczjje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Long bczjje;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hjqcb.bcjsrs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer bcjsrs;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hjqcb.bcjsje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Long bcjsje;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hjqcb.scjnrs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer scjnrs;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hjqcb.scjnje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Long scjnje;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hjqcb.bchnrs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer bchnrs;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hjqcb.bchnje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Long bchnje;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hjqcb.ssje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Long ssje;

<<<<<<< HEAD
    private String jedxzh;

=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hjqcb.jedxzh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private String jedxzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hjqcb.bjjkfs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String bjjkfs;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hjqcb.bjjkzt
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String bjjkzt;
<<<<<<< HEAD
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT-8")
=======

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hjqcb.rzrq
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Date rzrq;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hjqcb.hjywlx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String hjywlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hjqcb.hjbz
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private String hjbz;

<<<<<<< HEAD
    private String hjbz;

=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hjqcb.hjbh
     *
     * @return the value of hjqcb.hjbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getHjbh() {
        return hjbh;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hjqcb.hjbh
     *
     * @param hjbh the value for hjqcb.hjbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setHjbh(Integer hjbh) {
        this.hjbh = hjbh;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hjqcb.UnitInfoAccount
     *
     * @return the value of hjqcb.UnitInfoAccount
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getUnitinfoaccount() {
        return unitinfoaccount;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hjqcb.UnitInfoAccount
     *
     * @param unitinfoaccount the value for hjqcb.UnitInfoAccount
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setUnitinfoaccount(Integer unitinfoaccount) {
        this.unitinfoaccount = unitinfoaccount;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hjqcb.grzhbhs
     *
     * @return the value of hjqcb.grzhbhs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getGrzhbhs() {
        return grzhbhs;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hjqcb.grzhbhs
     *
     * @param grzhbhs the value for hjqcb.grzhbhs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setGrzhbhs(Integer grzhbhs) {
        this.grzhbhs = grzhbhs;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hjqcb.userId
     *
     * @return the value of hjqcb.userId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getUserid() {
        return userid;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hjqcb.userId
     *
     * @param userid the value for hjqcb.userId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hjqcb.gjind
     *
     * @return the value of hjqcb.gjind
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getGjind() {
        return gjind;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hjqcb.gjind
     *
     * @param gjind the value for hjqcb.gjind
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setGjind(String gjind) {
        this.gjind = gjind == null ? null : gjind.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hjqcb.jnmy
     *
     * @return the value of hjqcb.jnmy
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Date getJnmy() {
        return jnmy;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hjqcb.jnmy
     *
     * @param jnmy the value for hjqcb.jnmy
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setJnmy(Date jnmy) {
        this.jnmy = jnmy;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hjqcb.nhyf
     *
     * @return the value of hjqcb.nhyf
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getNhyf() {
        return nhyf;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hjqcb.nhyf
     *
     * @param nhyf the value for hjqcb.nhyf
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setNhyf(Integer nhyf) {
        this.nhyf = nhyf;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hjqcb.bjjzrq
     *
     * @return the value of hjqcb.bjjzrq
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Date getBjjzrq() {
        return bjjzrq;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hjqcb.bjjzrq
     *
     * @param bjjzrq the value for hjqcb.bjjzrq
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setBjjzrq(Date bjjzrq) {
        this.bjjzrq = bjjzrq;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hjqcb.bczjrs
     *
     * @return the value of hjqcb.bczjrs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getBczjrs() {
        return bczjrs;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hjqcb.bczjrs
     *
     * @param bczjrs the value for hjqcb.bczjrs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setBczjrs(Integer bczjrs) {
        this.bczjrs = bczjrs;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hjqcb.bczjje
     *
     * @return the value of hjqcb.bczjje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Long getBczjje() {
        return bczjje;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hjqcb.bczjje
     *
     * @param bczjje the value for hjqcb.bczjje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setBczjje(Long bczjje) {
        this.bczjje = bczjje;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hjqcb.bcjsrs
     *
     * @return the value of hjqcb.bcjsrs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getBcjsrs() {
        return bcjsrs;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hjqcb.bcjsrs
     *
     * @param bcjsrs the value for hjqcb.bcjsrs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setBcjsrs(Integer bcjsrs) {
        this.bcjsrs = bcjsrs;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hjqcb.bcjsje
     *
     * @return the value of hjqcb.bcjsje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Long getBcjsje() {
        return bcjsje;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hjqcb.bcjsje
     *
     * @param bcjsje the value for hjqcb.bcjsje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setBcjsje(Long bcjsje) {
        this.bcjsje = bcjsje;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hjqcb.scjnrs
     *
     * @return the value of hjqcb.scjnrs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getScjnrs() {
        return scjnrs;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hjqcb.scjnrs
     *
     * @param scjnrs the value for hjqcb.scjnrs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setScjnrs(Integer scjnrs) {
        this.scjnrs = scjnrs;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hjqcb.scjnje
     *
     * @return the value of hjqcb.scjnje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Long getScjnje() {
        return scjnje;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hjqcb.scjnje
     *
     * @param scjnje the value for hjqcb.scjnje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setScjnje(Long scjnje) {
        this.scjnje = scjnje;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hjqcb.bchnrs
     *
     * @return the value of hjqcb.bchnrs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getBchnrs() {
        return bchnrs;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hjqcb.bchnrs
     *
     * @param bchnrs the value for hjqcb.bchnrs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setBchnrs(Integer bchnrs) {
        this.bchnrs = bchnrs;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hjqcb.bchnje
     *
     * @return the value of hjqcb.bchnje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Long getBchnje() {
        return bchnje;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hjqcb.bchnje
     *
     * @param bchnje the value for hjqcb.bchnje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setBchnje(Long bchnje) {
        this.bchnje = bchnje;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hjqcb.ssje
     *
     * @return the value of hjqcb.ssje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Long getSsje() {
        return ssje;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hjqcb.ssje
     *
     * @param ssje the value for hjqcb.ssje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setSsje(Long ssje) {
        this.ssje = ssje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hjqcb.jedxzh
     *
     * @return the value of hjqcb.jedxzh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public String getJedxzh() {
        return jedxzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hjqcb.jedxzh
     *
     * @param jedxzh the value for hjqcb.jedxzh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setJedxzh(String jedxzh) {
        this.jedxzh = jedxzh == null ? null : jedxzh.trim();
    }

<<<<<<< HEAD
    public String getJedxzh() {
        return jedxzh;
    }

    public void setJedxzh(String jedxzh) {
        this.jedxzh = jedxzh == null ? null : jedxzh.trim();
    }

=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hjqcb.bjjkfs
     *
     * @return the value of hjqcb.bjjkfs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getBjjkfs() {
        return bjjkfs;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hjqcb.bjjkfs
     *
     * @param bjjkfs the value for hjqcb.bjjkfs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setBjjkfs(String bjjkfs) {
        this.bjjkfs = bjjkfs == null ? null : bjjkfs.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hjqcb.bjjkzt
     *
     * @return the value of hjqcb.bjjkzt
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getBjjkzt() {
        return bjjkzt;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hjqcb.bjjkzt
     *
     * @param bjjkzt the value for hjqcb.bjjkzt
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setBjjkzt(String bjjkzt) {
        this.bjjkzt = bjjkzt == null ? null : bjjkzt.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hjqcb.rzrq
     *
     * @return the value of hjqcb.rzrq
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Date getRzrq() {
        return rzrq;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hjqcb.rzrq
     *
     * @param rzrq the value for hjqcb.rzrq
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setRzrq(Date rzrq) {
        this.rzrq = rzrq;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hjqcb.hjywlx
     *
     * @return the value of hjqcb.hjywlx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getHjywlx() {
        return hjywlx;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hjqcb.hjywlx
     *
     * @param hjywlx the value for hjqcb.hjywlx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setHjywlx(String hjywlx) {
        this.hjywlx = hjywlx == null ? null : hjywlx.trim();
    }

<<<<<<< HEAD
    public String getHjbz() {
        return hjbz;
    }

=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hjqcb.hjbz
     *
     * @return the value of hjqcb.hjbz
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public String getHjbz() {
        return hjbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hjqcb.hjbz
     *
     * @param hjbz the value for hjqcb.hjbz
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setHjbz(String hjbz) {
        this.hjbz = hjbz == null ? null : hjbz.trim();
    }
}