package com.entity;

public class Individualpay {
<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individualpay.grzhbhs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer grzhbhs;

<<<<<<< HEAD
    private Integer unitinfoaccount;
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individualpay.UnitInfoAccount
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer unitinfoaccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individualpay.grzhbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer grzhbh;
>>>>>>> refs/remotes/origin/wangcc

<<<<<<< HEAD
    private Integer grzhbh;

=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individualpay.personalAccount
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String personalaccount;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individualpay.certificateType
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String certificatetype;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individualpay.IdNo
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String idno;

<<<<<<< HEAD
    private Integer personaldepositbase;
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individualpay.personalDepositBase
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private String personaldepositbase;
>>>>>>> refs/remotes/origin/wangcc

<<<<<<< HEAD
    private Integer unitratedeposit;
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individualpay.unitRateDeposit
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private String unitratedeposit;
>>>>>>> refs/remotes/origin/wangcc

<<<<<<< HEAD
    private Integer percontributionrate;
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individualpay.perContributionRate
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private String percontributionrate;
>>>>>>> refs/remotes/origin/wangcc

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individualpay.openAccountStatus
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String openaccountstatus;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individualpay.openingDate
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String openingdate;

<<<<<<< HEAD
    private Integer peraccountbalance;
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individualpay.perAccountBalance
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private String peraccountbalance;
>>>>>>> refs/remotes/origin/wangcc

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individualpay.lastYearLeftBalance
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String lastyearleftbalance;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individualpay.thatYearLeftBalance
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String thatyearleftbalance;

<<<<<<< HEAD
    private Integer monpayamount;
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individualpay.monPayAmount
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private String monpayamount;
>>>>>>> refs/remotes/origin/wangcc

<<<<<<< HEAD
    private Integer unitmonpayamount;
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individualpay.unitMonPayAmount
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private String unitmonpayamount;
>>>>>>> refs/remotes/origin/wangcc

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individualpay.pinHouseholdsDate
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String pinhouseholdsdate;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individualpay.gfbankAccount
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer gfbankaccount;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individualpay.bankName
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String bankname;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individualpay.bankNameNum
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String banknamenum;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individualpay.frozenType
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String frozentype;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individualpay.AccumulationRegularly
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String accumulationregularly;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individualpay.currentAccumulation
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String currentaccumulation;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individualpay.lastYearAccumulationRegularly
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String lastyearaccumulationregularly;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individualpay.lastYearcurrentAccumulation
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String lastyearcurrentaccumulation;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individualpay.annualInterest
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String annualinterest;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individualpay.demandInterest
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String demandinterest;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individualpay.annualInterestAnd
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String annualinterestand;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individualpay.demandInterestAnd
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String demandinterestand;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column individualpay.extractThisYear
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String extractthisyear;

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individualpay.grzhbhs
     *
     * @return the value of individualpay.grzhbhs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getGrzhbhs() {
        return grzhbhs;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individualpay.grzhbhs
     *
     * @param grzhbhs the value for individualpay.grzhbhs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setGrzhbhs(Integer grzhbhs) {
        this.grzhbhs = grzhbhs;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individualpay.UnitInfoAccount
     *
     * @return the value of individualpay.UnitInfoAccount
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getUnitinfoaccount() {
        return unitinfoaccount;
    }

<<<<<<< HEAD
    public void setUnitinfoaccount(Integer unitinfoaccount) {
        this.unitinfoaccount = unitinfoaccount;
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individualpay.UnitInfoAccount
     *
     * @param unitinfoaccount the value for individualpay.UnitInfoAccount
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setUnitinfoaccount(Integer unitinfoaccount) {
        this.unitinfoaccount = unitinfoaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individualpay.grzhbh
     *
     * @return the value of individualpay.grzhbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getGrzhbh() {
        return grzhbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individualpay.grzhbh
     *
     * @param grzhbh the value for individualpay.grzhbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setGrzhbh(Integer grzhbh) {
        this.grzhbh = grzhbh;
>>>>>>> refs/remotes/origin/wangcc
    }

<<<<<<< HEAD
    public Integer getGrzhbh() {
        return grzhbh;
    }

    public void setGrzhbh(Integer grzhbh) {
        this.grzhbh = grzhbh;
    }

=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individualpay.personalAccount
     *
     * @return the value of individualpay.personalAccount
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getPersonalaccount() {
        return personalaccount;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individualpay.personalAccount
     *
     * @param personalaccount the value for individualpay.personalAccount
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setPersonalaccount(String personalaccount) {
        this.personalaccount = personalaccount == null ? null : personalaccount.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individualpay.certificateType
     *
     * @return the value of individualpay.certificateType
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getCertificatetype() {
        return certificatetype;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individualpay.certificateType
     *
     * @param certificatetype the value for individualpay.certificateType
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setCertificatetype(String certificatetype) {
        this.certificatetype = certificatetype == null ? null : certificatetype.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individualpay.IdNo
     *
     * @return the value of individualpay.IdNo
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getIdno() {
        return idno;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individualpay.IdNo
     *
     * @param idno the value for individualpay.IdNo
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setIdno(String idno) {
        this.idno = idno == null ? null : idno.trim();
    }

<<<<<<< HEAD
   
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individualpay.personalDepositBase
     *
     * @return the value of individualpay.personalDepositBase
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public String getPersonaldepositbase() {
        return personaldepositbase;
    }
>>>>>>> refs/remotes/origin/wangcc

<<<<<<< HEAD
   
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individualpay.personalDepositBase
     *
     * @param personaldepositbase the value for individualpay.personalDepositBase
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setPersonaldepositbase(String personaldepositbase) {
        this.personaldepositbase = personaldepositbase == null ? null : personaldepositbase.trim();
    }
>>>>>>> refs/remotes/origin/wangcc

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individualpay.unitRateDeposit
     *
     * @return the value of individualpay.unitRateDeposit
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public String getUnitratedeposit() {
        return unitratedeposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individualpay.unitRateDeposit
     *
     * @param unitratedeposit the value for individualpay.unitRateDeposit
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setUnitratedeposit(String unitratedeposit) {
        this.unitratedeposit = unitratedeposit == null ? null : unitratedeposit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individualpay.perContributionRate
     *
     * @return the value of individualpay.perContributionRate
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public String getPercontributionrate() {
        return percontributionrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individualpay.perContributionRate
     *
     * @param percontributionrate the value for individualpay.perContributionRate
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setPercontributionrate(String percontributionrate) {
        this.percontributionrate = percontributionrate == null ? null : percontributionrate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individualpay.openAccountStatus
     *
     * @return the value of individualpay.openAccountStatus
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getOpenaccountstatus() {
        return openaccountstatus;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individualpay.openAccountStatus
     *
     * @param openaccountstatus the value for individualpay.openAccountStatus
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setOpenaccountstatus(String openaccountstatus) {
        this.openaccountstatus = openaccountstatus == null ? null : openaccountstatus.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individualpay.openingDate
     *
     * @return the value of individualpay.openingDate
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getOpeningdate() {
        return openingdate;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individualpay.openingDate
     *
     * @param openingdate the value for individualpay.openingDate
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setOpeningdate(String openingdate) {
        this.openingdate = openingdate == null ? null : openingdate.trim();
    }

<<<<<<< HEAD
   
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individualpay.perAccountBalance
     *
     * @return the value of individualpay.perAccountBalance
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public String getPeraccountbalance() {
        return peraccountbalance;
    }
>>>>>>> refs/remotes/origin/wangcc

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individualpay.perAccountBalance
     *
     * @param peraccountbalance the value for individualpay.perAccountBalance
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setPeraccountbalance(String peraccountbalance) {
        this.peraccountbalance = peraccountbalance == null ? null : peraccountbalance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individualpay.lastYearLeftBalance
     *
     * @return the value of individualpay.lastYearLeftBalance
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getLastyearleftbalance() {
        return lastyearleftbalance;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individualpay.lastYearLeftBalance
     *
     * @param lastyearleftbalance the value for individualpay.lastYearLeftBalance
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setLastyearleftbalance(String lastyearleftbalance) {
        this.lastyearleftbalance = lastyearleftbalance == null ? null : lastyearleftbalance.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individualpay.thatYearLeftBalance
     *
     * @return the value of individualpay.thatYearLeftBalance
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getThatyearleftbalance() {
        return thatyearleftbalance;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individualpay.thatYearLeftBalance
     *
     * @param thatyearleftbalance the value for individualpay.thatYearLeftBalance
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setThatyearleftbalance(String thatyearleftbalance) {
        this.thatyearleftbalance = thatyearleftbalance == null ? null : thatyearleftbalance.trim();
    }

<<<<<<< HEAD
    
   
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individualpay.monPayAmount
     *
     * @return the value of individualpay.monPayAmount
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public String getMonpayamount() {
        return monpayamount;
    }
>>>>>>> refs/remotes/origin/wangcc

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individualpay.monPayAmount
     *
     * @param monpayamount the value for individualpay.monPayAmount
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setMonpayamount(String monpayamount) {
        this.monpayamount = monpayamount == null ? null : monpayamount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individualpay.unitMonPayAmount
     *
     * @return the value of individualpay.unitMonPayAmount
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public String getUnitmonpayamount() {
        return unitmonpayamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individualpay.unitMonPayAmount
     *
     * @param unitmonpayamount the value for individualpay.unitMonPayAmount
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setUnitmonpayamount(String unitmonpayamount) {
        this.unitmonpayamount = unitmonpayamount == null ? null : unitmonpayamount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individualpay.pinHouseholdsDate
     *
     * @return the value of individualpay.pinHouseholdsDate
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getPinhouseholdsdate() {
        return pinhouseholdsdate;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individualpay.pinHouseholdsDate
     *
     * @param pinhouseholdsdate the value for individualpay.pinHouseholdsDate
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setPinhouseholdsdate(String pinhouseholdsdate) {
        this.pinhouseholdsdate = pinhouseholdsdate == null ? null : pinhouseholdsdate.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individualpay.gfbankAccount
     *
     * @return the value of individualpay.gfbankAccount
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getGfbankaccount() {
        return gfbankaccount;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individualpay.gfbankAccount
     *
     * @param gfbankaccount the value for individualpay.gfbankAccount
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setGfbankaccount(Integer gfbankaccount) {
        this.gfbankaccount = gfbankaccount;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individualpay.bankName
     *
     * @return the value of individualpay.bankName
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getBankname() {
        return bankname;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individualpay.bankName
     *
     * @param bankname the value for individualpay.bankName
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setBankname(String bankname) {
        this.bankname = bankname == null ? null : bankname.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individualpay.bankNameNum
     *
     * @return the value of individualpay.bankNameNum
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getBanknamenum() {
        return banknamenum;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individualpay.bankNameNum
     *
     * @param banknamenum the value for individualpay.bankNameNum
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setBanknamenum(String banknamenum) {
        this.banknamenum = banknamenum == null ? null : banknamenum.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individualpay.frozenType
     *
     * @return the value of individualpay.frozenType
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getFrozentype() {
        return frozentype;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individualpay.frozenType
     *
     * @param frozentype the value for individualpay.frozenType
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setFrozentype(String frozentype) {
        this.frozentype = frozentype == null ? null : frozentype.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individualpay.AccumulationRegularly
     *
     * @return the value of individualpay.AccumulationRegularly
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getAccumulationregularly() {
        return accumulationregularly;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individualpay.AccumulationRegularly
     *
     * @param accumulationregularly the value for individualpay.AccumulationRegularly
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setAccumulationregularly(String accumulationregularly) {
        this.accumulationregularly = accumulationregularly == null ? null : accumulationregularly.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individualpay.currentAccumulation
     *
     * @return the value of individualpay.currentAccumulation
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getCurrentaccumulation() {
        return currentaccumulation;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individualpay.currentAccumulation
     *
     * @param currentaccumulation the value for individualpay.currentAccumulation
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setCurrentaccumulation(String currentaccumulation) {
        this.currentaccumulation = currentaccumulation == null ? null : currentaccumulation.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individualpay.lastYearAccumulationRegularly
     *
     * @return the value of individualpay.lastYearAccumulationRegularly
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getLastyearaccumulationregularly() {
        return lastyearaccumulationregularly;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individualpay.lastYearAccumulationRegularly
     *
     * @param lastyearaccumulationregularly the value for individualpay.lastYearAccumulationRegularly
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setLastyearaccumulationregularly(String lastyearaccumulationregularly) {
        this.lastyearaccumulationregularly = lastyearaccumulationregularly == null ? null : lastyearaccumulationregularly.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individualpay.lastYearcurrentAccumulation
     *
     * @return the value of individualpay.lastYearcurrentAccumulation
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getLastyearcurrentaccumulation() {
        return lastyearcurrentaccumulation;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individualpay.lastYearcurrentAccumulation
     *
     * @param lastyearcurrentaccumulation the value for individualpay.lastYearcurrentAccumulation
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setLastyearcurrentaccumulation(String lastyearcurrentaccumulation) {
        this.lastyearcurrentaccumulation = lastyearcurrentaccumulation == null ? null : lastyearcurrentaccumulation.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individualpay.annualInterest
     *
     * @return the value of individualpay.annualInterest
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getAnnualinterest() {
        return annualinterest;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individualpay.annualInterest
     *
     * @param annualinterest the value for individualpay.annualInterest
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setAnnualinterest(String annualinterest) {
        this.annualinterest = annualinterest == null ? null : annualinterest.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individualpay.demandInterest
     *
     * @return the value of individualpay.demandInterest
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getDemandinterest() {
        return demandinterest;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individualpay.demandInterest
     *
     * @param demandinterest the value for individualpay.demandInterest
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setDemandinterest(String demandinterest) {
        this.demandinterest = demandinterest == null ? null : demandinterest.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individualpay.annualInterestAnd
     *
     * @return the value of individualpay.annualInterestAnd
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getAnnualinterestand() {
        return annualinterestand;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individualpay.annualInterestAnd
     *
     * @param annualinterestand the value for individualpay.annualInterestAnd
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setAnnualinterestand(String annualinterestand) {
        this.annualinterestand = annualinterestand == null ? null : annualinterestand.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individualpay.demandInterestAnd
     *
     * @return the value of individualpay.demandInterestAnd
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getDemandinterestand() {
        return demandinterestand;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individualpay.demandInterestAnd
     *
     * @param demandinterestand the value for individualpay.demandInterestAnd
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setDemandinterestand(String demandinterestand) {
        this.demandinterestand = demandinterestand == null ? null : demandinterestand.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column individualpay.extractThisYear
     *
     * @return the value of individualpay.extractThisYear
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getExtractthisyear() {
        return extractthisyear;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column individualpay.extractThisYear
     *
     * @param extractthisyear the value for individualpay.extractThisYear
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setExtractthisyear(String extractthisyear) {
        this.extractthisyear = extractthisyear == null ? null : extractthisyear.trim();
    }

	public Integer getPersonaldepositbase() {
		return personaldepositbase;
	}

	public void setPersonaldepositbase(Integer personaldepositbase) {
		this.personaldepositbase = personaldepositbase;
	}

	public Integer getUnitratedeposit() {
		return unitratedeposit;
	}

	public void setUnitratedeposit(Integer unitratedeposit) {
		this.unitratedeposit = unitratedeposit;
	}

	public Integer getPercontributionrate() {
		return percontributionrate;
	}

	public void setPercontributionrate(Integer percontributionrate) {
		this.percontributionrate = percontributionrate;
	}

	public Integer getPeraccountbalance() {
		return peraccountbalance;
	}

	public void setPeraccountbalance(Integer peraccountbalance) {
		this.peraccountbalance = peraccountbalance;
	}

	public Integer getMonpayamount() {
		return monpayamount;
	}

	public void setMonpayamount(Integer monpayamount) {
		this.monpayamount = monpayamount;
	}

	public Integer getUnitmonpayamount() {
		return unitmonpayamount;
	}

	public void setUnitmonpayamount(Integer unitmonpayamount) {
		this.unitmonpayamount = unitmonpayamount;
	}
    
}