package com.entity;

public class Marstatuts {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column marstatuts.id
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column marstatuts.maritalStatus
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private String maritalstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column marstatuts.id
     *
     * @return the value of marstatuts.id
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column marstatuts.id
     *
     * @param id the value for marstatuts.id
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column marstatuts.maritalStatus
     *
     * @return the value of marstatuts.maritalStatus
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public String getMaritalstatus() {
        return maritalstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column marstatuts.maritalStatus
     *
     * @param maritalstatus the value for marstatuts.maritalStatus
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setMaritalstatus(String maritalstatus) {
        this.maritalstatus = maritalstatus == null ? null : maritalstatus.trim();
    }
}