package com.entity;

public class Messagement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messagement.messageId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer messageid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messagement.userId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messagement.messageContent
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private String messagecontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messagement.readStatus
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private String readstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messagement.senderNum
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private String sendernum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messagement.sendTime
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private String sendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messagement.recipientNum
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private String recipientnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messagement.readTime
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private String readtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messagement.messageId
     *
     * @return the value of messagement.messageId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getMessageid() {
        return messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messagement.messageId
     *
     * @param messageid the value for messagement.messageId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setMessageid(Integer messageid) {
        this.messageid = messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messagement.userId
     *
     * @return the value of messagement.userId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messagement.userId
     *
     * @param userid the value for messagement.userId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messagement.messageContent
     *
     * @return the value of messagement.messageContent
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public String getMessagecontent() {
        return messagecontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messagement.messageContent
     *
     * @param messagecontent the value for messagement.messageContent
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setMessagecontent(String messagecontent) {
        this.messagecontent = messagecontent == null ? null : messagecontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messagement.readStatus
     *
     * @return the value of messagement.readStatus
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public String getReadstatus() {
        return readstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messagement.readStatus
     *
     * @param readstatus the value for messagement.readStatus
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setReadstatus(String readstatus) {
        this.readstatus = readstatus == null ? null : readstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messagement.senderNum
     *
     * @return the value of messagement.senderNum
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public String getSendernum() {
        return sendernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messagement.senderNum
     *
     * @param sendernum the value for messagement.senderNum
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setSendernum(String sendernum) {
        this.sendernum = sendernum == null ? null : sendernum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messagement.sendTime
     *
     * @return the value of messagement.sendTime
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public String getSendtime() {
        return sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messagement.sendTime
     *
     * @param sendtime the value for messagement.sendTime
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setSendtime(String sendtime) {
        this.sendtime = sendtime == null ? null : sendtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messagement.recipientNum
     *
     * @return the value of messagement.recipientNum
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public String getRecipientnum() {
        return recipientnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messagement.recipientNum
     *
     * @param recipientnum the value for messagement.recipientNum
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setRecipientnum(String recipientnum) {
        this.recipientnum = recipientnum == null ? null : recipientnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messagement.readTime
     *
     * @return the value of messagement.readTime
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public String getReadtime() {
        return readtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messagement.readTime
     *
     * @param readtime the value for messagement.readTime
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setReadtime(String readtime) {
        this.readtime = readtime == null ? null : readtime.trim();
    }
}