package com.entity;

public class Networkinfo {
<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column networkinfo.netinfoId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer netinfoid;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column networkinfo.userId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer userid;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column networkinfo.NetworkName
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String networkname;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column networkinfo.NetworkAddress
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String networkaddress;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column networkinfo.NetworkPhone
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String networkphone;

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column networkinfo.netinfoId
     *
     * @return the value of networkinfo.netinfoId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getNetinfoid() {
        return netinfoid;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column networkinfo.netinfoId
     *
     * @param netinfoid the value for networkinfo.netinfoId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setNetinfoid(Integer netinfoid) {
        this.netinfoid = netinfoid;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column networkinfo.userId
     *
     * @return the value of networkinfo.userId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getUserid() {
        return userid;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column networkinfo.userId
     *
     * @param userid the value for networkinfo.userId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column networkinfo.NetworkName
     *
     * @return the value of networkinfo.NetworkName
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getNetworkname() {
        return networkname;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column networkinfo.NetworkName
     *
     * @param networkname the value for networkinfo.NetworkName
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setNetworkname(String networkname) {
        this.networkname = networkname == null ? null : networkname.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column networkinfo.NetworkAddress
     *
     * @return the value of networkinfo.NetworkAddress
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getNetworkaddress() {
        return networkaddress;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column networkinfo.NetworkAddress
     *
     * @param networkaddress the value for networkinfo.NetworkAddress
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setNetworkaddress(String networkaddress) {
        this.networkaddress = networkaddress == null ? null : networkaddress.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column networkinfo.NetworkPhone
     *
     * @return the value of networkinfo.NetworkPhone
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getNetworkphone() {
        return networkphone;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column networkinfo.NetworkPhone
     *
     * @param networkphone the value for networkinfo.NetworkPhone
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setNetworkphone(String networkphone) {
        this.networkphone = networkphone == null ? null : networkphone.trim();
    }
}