package com.entity;

import java.util.Date;

public class Overdue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column overdue.yqdjbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer yqdjbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column overdue.dkbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer dkbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column overdue.ywbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private String ywbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column overdue.yqqc
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer yqqc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column overdue.grfdyqbj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer grfdyqbj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column overdue.grfdyqlx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer grfdyqlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column overdue.yqfx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer yqfx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column overdue.ssrq
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Date ssrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column overdue.hkqc
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer hkqc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column overdue.ssyqbjje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer ssyqbjje;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column overdue.ssyqlxje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer ssyqlxje;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column overdue.ssyqfxje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer ssyqfxje;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column overdue.yqztzs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private String yqztzs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column overdue.sfetf
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private String sfetf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column overdue.zxkkrq
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Date zxkkrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column overdue.djsj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Date djsj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overdue.yqdjbh
     *
     * @return the value of overdue.yqdjbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getYqdjbh() {
        return yqdjbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overdue.yqdjbh
     *
     * @param yqdjbh the value for overdue.yqdjbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setYqdjbh(Integer yqdjbh) {
        this.yqdjbh = yqdjbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overdue.dkbh
     *
     * @return the value of overdue.dkbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getDkbh() {
        return dkbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overdue.dkbh
     *
     * @param dkbh the value for overdue.dkbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setDkbh(Integer dkbh) {
        this.dkbh = dkbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overdue.ywbh
     *
     * @return the value of overdue.ywbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public String getYwbh() {
        return ywbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overdue.ywbh
     *
     * @param ywbh the value for overdue.ywbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setYwbh(String ywbh) {
        this.ywbh = ywbh == null ? null : ywbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overdue.yqqc
     *
     * @return the value of overdue.yqqc
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getYqqc() {
        return yqqc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overdue.yqqc
     *
     * @param yqqc the value for overdue.yqqc
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setYqqc(Integer yqqc) {
        this.yqqc = yqqc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overdue.grfdyqbj
     *
     * @return the value of overdue.grfdyqbj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getGrfdyqbj() {
        return grfdyqbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overdue.grfdyqbj
     *
     * @param grfdyqbj the value for overdue.grfdyqbj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setGrfdyqbj(Integer grfdyqbj) {
        this.grfdyqbj = grfdyqbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overdue.grfdyqlx
     *
     * @return the value of overdue.grfdyqlx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getGrfdyqlx() {
        return grfdyqlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overdue.grfdyqlx
     *
     * @param grfdyqlx the value for overdue.grfdyqlx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setGrfdyqlx(Integer grfdyqlx) {
        this.grfdyqlx = grfdyqlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overdue.yqfx
     *
     * @return the value of overdue.yqfx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getYqfx() {
        return yqfx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overdue.yqfx
     *
     * @param yqfx the value for overdue.yqfx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setYqfx(Integer yqfx) {
        this.yqfx = yqfx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overdue.ssrq
     *
     * @return the value of overdue.ssrq
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Date getSsrq() {
        return ssrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overdue.ssrq
     *
     * @param ssrq the value for overdue.ssrq
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setSsrq(Date ssrq) {
        this.ssrq = ssrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overdue.hkqc
     *
     * @return the value of overdue.hkqc
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getHkqc() {
        return hkqc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overdue.hkqc
     *
     * @param hkqc the value for overdue.hkqc
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setHkqc(Integer hkqc) {
        this.hkqc = hkqc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overdue.ssyqbjje
     *
     * @return the value of overdue.ssyqbjje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getSsyqbjje() {
        return ssyqbjje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overdue.ssyqbjje
     *
     * @param ssyqbjje the value for overdue.ssyqbjje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setSsyqbjje(Integer ssyqbjje) {
        this.ssyqbjje = ssyqbjje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overdue.ssyqlxje
     *
     * @return the value of overdue.ssyqlxje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getSsyqlxje() {
        return ssyqlxje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overdue.ssyqlxje
     *
     * @param ssyqlxje the value for overdue.ssyqlxje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setSsyqlxje(Integer ssyqlxje) {
        this.ssyqlxje = ssyqlxje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overdue.ssyqfxje
     *
     * @return the value of overdue.ssyqfxje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getSsyqfxje() {
        return ssyqfxje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overdue.ssyqfxje
     *
     * @param ssyqfxje the value for overdue.ssyqfxje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setSsyqfxje(Integer ssyqfxje) {
        this.ssyqfxje = ssyqfxje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overdue.yqztzs
     *
     * @return the value of overdue.yqztzs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public String getYqztzs() {
        return yqztzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overdue.yqztzs
     *
     * @param yqztzs the value for overdue.yqztzs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setYqztzs(String yqztzs) {
        this.yqztzs = yqztzs == null ? null : yqztzs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overdue.sfetf
     *
     * @return the value of overdue.sfetf
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public String getSfetf() {
        return sfetf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overdue.sfetf
     *
     * @param sfetf the value for overdue.sfetf
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setSfetf(String sfetf) {
        this.sfetf = sfetf == null ? null : sfetf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overdue.zxkkrq
     *
     * @return the value of overdue.zxkkrq
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Date getZxkkrq() {
        return zxkkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overdue.zxkkrq
     *
     * @param zxkkrq the value for overdue.zxkkrq
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setZxkkrq(Date zxkkrq) {
        this.zxkkrq = zxkkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overdue.djsj
     *
     * @return the value of overdue.djsj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Date getDjsj() {
        return djsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overdue.djsj
     *
     * @param djsj the value for overdue.djsj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setDjsj(Date djsj) {
        this.djsj = djsj;
    }
}