package com.entity;

public class Peraccount {
<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peraccount.grzhbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer grzhbh;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peraccount.zhztbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer zhztbh;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peraccount.UnitpositionId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer unitpositionid;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peraccount.UnitInfoId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer unitinfoid;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peraccount.netinfoId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer netinfoid;

<<<<<<< HEAD
    private Integer unitinfoaccount;

    private Integer grzhbhs;

=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peraccount.UnitInfoAccount
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer unitinfoaccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peraccount.grzhbhs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer grzhbhs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peraccount.peracId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String peracid;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peraccount.peracloginpw
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String peracloginpw;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peraccount.peracTransactionpw
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String peractransactionpw;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peraccount.peracBalance
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer peracbalance;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peraccount.peracUpdatestatus
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String peracupdatestatus;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peraccount.bkname
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String bkname;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peraccount.bksex
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String bksex;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peraccount.phoneNum
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String phonenum;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peraccount.IdType
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String idtype;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peraccount.IdNumbers
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String idnumbers;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peraccount.birthday
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String birthday;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peraccount.marital
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String marital;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peraccount.education
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String education;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peraccount.email
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String email;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peraccount.postcode
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String postcode;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peraccount.address
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String address;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peraccount.monthlyProfit
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer monthlyprofit;

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peraccount.grzhbh
     *
     * @return the value of peraccount.grzhbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getGrzhbh() {
        return grzhbh;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peraccount.grzhbh
     *
     * @param grzhbh the value for peraccount.grzhbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setGrzhbh(Integer grzhbh) {
        this.grzhbh = grzhbh;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peraccount.zhztbh
     *
     * @return the value of peraccount.zhztbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getZhztbh() {
        return zhztbh;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peraccount.zhztbh
     *
     * @param zhztbh the value for peraccount.zhztbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setZhztbh(Integer zhztbh) {
        this.zhztbh = zhztbh;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peraccount.UnitpositionId
     *
     * @return the value of peraccount.UnitpositionId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getUnitpositionid() {
        return unitpositionid;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peraccount.UnitpositionId
     *
     * @param unitpositionid the value for peraccount.UnitpositionId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setUnitpositionid(Integer unitpositionid) {
        this.unitpositionid = unitpositionid;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peraccount.UnitInfoId
     *
     * @return the value of peraccount.UnitInfoId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getUnitinfoid() {
        return unitinfoid;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peraccount.UnitInfoId
     *
     * @param unitinfoid the value for peraccount.UnitInfoId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setUnitinfoid(Integer unitinfoid) {
        this.unitinfoid = unitinfoid;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peraccount.netinfoId
     *
     * @return the value of peraccount.netinfoId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getNetinfoid() {
        return netinfoid;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peraccount.netinfoId
     *
     * @param netinfoid the value for peraccount.netinfoId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setNetinfoid(Integer netinfoid) {
        this.netinfoid = netinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peraccount.UnitInfoAccount
     *
     * @return the value of peraccount.UnitInfoAccount
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getUnitinfoaccount() {
        return unitinfoaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peraccount.UnitInfoAccount
     *
     * @param unitinfoaccount the value for peraccount.UnitInfoAccount
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setUnitinfoaccount(Integer unitinfoaccount) {
        this.unitinfoaccount = unitinfoaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peraccount.grzhbhs
     *
     * @return the value of peraccount.grzhbhs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getGrzhbhs() {
        return grzhbhs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peraccount.grzhbhs
     *
     * @param grzhbhs the value for peraccount.grzhbhs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setGrzhbhs(Integer grzhbhs) {
        this.grzhbhs = grzhbhs;
    }

<<<<<<< HEAD
    public Integer getUnitinfoaccount() {
        return unitinfoaccount;
    }

    public void setUnitinfoaccount(Integer unitinfoaccount) {
        this.unitinfoaccount = unitinfoaccount;
    }

    public Integer getGrzhbhs() {
        return grzhbhs;
    }

    public void setGrzhbhs(Integer grzhbhs) {
        this.grzhbhs = grzhbhs;
    }

=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peraccount.peracId
     *
     * @return the value of peraccount.peracId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getPeracid() {
        return peracid;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peraccount.peracId
     *
     * @param peracid the value for peraccount.peracId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setPeracid(String peracid) {
        this.peracid = peracid == null ? null : peracid.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peraccount.peracloginpw
     *
     * @return the value of peraccount.peracloginpw
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getPeracloginpw() {
        return peracloginpw;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peraccount.peracloginpw
     *
     * @param peracloginpw the value for peraccount.peracloginpw
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setPeracloginpw(String peracloginpw) {
        this.peracloginpw = peracloginpw == null ? null : peracloginpw.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peraccount.peracTransactionpw
     *
     * @return the value of peraccount.peracTransactionpw
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getPeractransactionpw() {
        return peractransactionpw;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peraccount.peracTransactionpw
     *
     * @param peractransactionpw the value for peraccount.peracTransactionpw
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setPeractransactionpw(String peractransactionpw) {
        this.peractransactionpw = peractransactionpw == null ? null : peractransactionpw.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peraccount.peracBalance
     *
     * @return the value of peraccount.peracBalance
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getPeracbalance() {
        return peracbalance;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peraccount.peracBalance
     *
     * @param peracbalance the value for peraccount.peracBalance
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setPeracbalance(Integer peracbalance) {
        this.peracbalance = peracbalance;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peraccount.peracUpdatestatus
     *
     * @return the value of peraccount.peracUpdatestatus
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getPeracupdatestatus() {
        return peracupdatestatus;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peraccount.peracUpdatestatus
     *
     * @param peracupdatestatus the value for peraccount.peracUpdatestatus
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setPeracupdatestatus(String peracupdatestatus) {
        this.peracupdatestatus = peracupdatestatus == null ? null : peracupdatestatus.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peraccount.bkname
     *
     * @return the value of peraccount.bkname
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getBkname() {
        return bkname;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peraccount.bkname
     *
     * @param bkname the value for peraccount.bkname
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setBkname(String bkname) {
        this.bkname = bkname == null ? null : bkname.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peraccount.bksex
     *
     * @return the value of peraccount.bksex
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getBksex() {
        return bksex;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peraccount.bksex
     *
     * @param bksex the value for peraccount.bksex
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setBksex(String bksex) {
        this.bksex = bksex == null ? null : bksex.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peraccount.phoneNum
     *
     * @return the value of peraccount.phoneNum
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getPhonenum() {
        return phonenum;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peraccount.phoneNum
     *
     * @param phonenum the value for peraccount.phoneNum
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setPhonenum(String phonenum) {
        this.phonenum = phonenum == null ? null : phonenum.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peraccount.IdType
     *
     * @return the value of peraccount.IdType
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getIdtype() {
        return idtype;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peraccount.IdType
     *
     * @param idtype the value for peraccount.IdType
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setIdtype(String idtype) {
        this.idtype = idtype == null ? null : idtype.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peraccount.IdNumbers
     *
     * @return the value of peraccount.IdNumbers
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getIdnumbers() {
        return idnumbers;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peraccount.IdNumbers
     *
     * @param idnumbers the value for peraccount.IdNumbers
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setIdnumbers(String idnumbers) {
        this.idnumbers = idnumbers == null ? null : idnumbers.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peraccount.birthday
     *
     * @return the value of peraccount.birthday
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getBirthday() {
        return birthday;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peraccount.birthday
     *
     * @param birthday the value for peraccount.birthday
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peraccount.marital
     *
     * @return the value of peraccount.marital
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getMarital() {
        return marital;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peraccount.marital
     *
     * @param marital the value for peraccount.marital
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setMarital(String marital) {
        this.marital = marital == null ? null : marital.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peraccount.education
     *
     * @return the value of peraccount.education
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getEducation() {
        return education;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peraccount.education
     *
     * @param education the value for peraccount.education
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peraccount.email
     *
     * @return the value of peraccount.email
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getEmail() {
        return email;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peraccount.email
     *
     * @param email the value for peraccount.email
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peraccount.postcode
     *
     * @return the value of peraccount.postcode
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getPostcode() {
        return postcode;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peraccount.postcode
     *
     * @param postcode the value for peraccount.postcode
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peraccount.address
     *
     * @return the value of peraccount.address
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getAddress() {
        return address;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peraccount.address
     *
     * @param address the value for peraccount.address
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peraccount.monthlyProfit
     *
     * @return the value of peraccount.monthlyProfit
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getMonthlyprofit() {
        return monthlyprofit;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peraccount.monthlyProfit
     *
     * @param monthlyprofit the value for peraccount.monthlyProfit
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setMonthlyprofit(Integer monthlyprofit) {
        this.monthlyprofit = monthlyprofit;
    }

	public Peraccount(Integer grzhbh, Integer zhztbh, Integer unitpositionid, Integer unitinfoid, Integer netinfoid,
			Integer unitinfoaccount, Integer grzhbhs, String peracid, String peracloginpw, String peractransactionpw,
			Integer peracbalance, String peracupdatestatus, String bkname, String bksex, String phonenum, String idtype,
			String idnumbers, String birthday, String marital, String education, String email, String postcode,
			String address, Integer monthlyprofit) {
		super();
		this.grzhbh = grzhbh;
		this.zhztbh = zhztbh;
		this.unitpositionid = unitpositionid;
		this.unitinfoid = unitinfoid;
		this.netinfoid = netinfoid;
		this.unitinfoaccount = unitinfoaccount;
		this.grzhbhs = grzhbhs;
		this.peracid = peracid;
		this.peracloginpw = peracloginpw;
		this.peractransactionpw = peractransactionpw;
		this.peracbalance = peracbalance;
		this.peracupdatestatus = peracupdatestatus;
		this.bkname = bkname;
		this.bksex = bksex;
		this.phonenum = phonenum;
		this.idtype = idtype;
		this.idnumbers = idnumbers;
		this.birthday = birthday;
		this.marital = marital;
		this.education = education;
		this.email = email;
		this.postcode = postcode;
		this.address = address;
		this.monthlyprofit = monthlyprofit;
	}

	public Peraccount() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Peraccount(Integer grzhbh, Integer zhztbh) {
		super();
		this.grzhbh = grzhbh;
		this.zhztbh = zhztbh;
	}
}