package com.entity;

import java.util.Date;

public class Perbusiness {
<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perbusiness.perbuid
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer perbuid;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perbusiness.grzhbhs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer grzhbhs;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perbusiness.netinfoId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer netinfoid;

<<<<<<< HEAD
    private Integer grzhbh;

=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perbusiness.grzhbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer grzhbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perbusiness.grpersonIds
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String grpersonids;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perbusiness.grperbuTime
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Date grperbutime;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perbusiness.grperbuType
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String grperbutype;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perbusiness.perbuLimit
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer perbulimit;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perbusiness.retrievingMeans
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String retrievingmeans;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perbusiness.grapprovalStatuss
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String grapprovalstatuss;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perbusiness.SettlementStatus
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String settlementstatus;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perbusiness.strike
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String strike;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perbusiness.unitAdvancep
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer unitadvancep;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perbusiness.personAdvancep
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer personadvancep;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perbusiness.bglx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String bglx;

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perbusiness.perbuid
     *
     * @return the value of perbusiness.perbuid
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getPerbuid() {
        return perbuid;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perbusiness.perbuid
     *
     * @param perbuid the value for perbusiness.perbuid
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setPerbuid(Integer perbuid) {
        this.perbuid = perbuid;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perbusiness.grzhbhs
     *
     * @return the value of perbusiness.grzhbhs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getGrzhbhs() {
        return grzhbhs;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perbusiness.grzhbhs
     *
     * @param grzhbhs the value for perbusiness.grzhbhs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setGrzhbhs(Integer grzhbhs) {
        this.grzhbhs = grzhbhs;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perbusiness.netinfoId
     *
     * @return the value of perbusiness.netinfoId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getNetinfoid() {
        return netinfoid;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perbusiness.netinfoId
     *
     * @param netinfoid the value for perbusiness.netinfoId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setNetinfoid(Integer netinfoid) {
        this.netinfoid = netinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perbusiness.grzhbh
     *
     * @return the value of perbusiness.grzhbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getGrzhbh() {
        return grzhbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perbusiness.grzhbh
     *
     * @param grzhbh the value for perbusiness.grzhbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setGrzhbh(Integer grzhbh) {
        this.grzhbh = grzhbh;
    }

<<<<<<< HEAD
    public Integer getGrzhbh() {
        return grzhbh;
    }

    public void setGrzhbh(Integer grzhbh) {
        this.grzhbh = grzhbh;
    }

=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perbusiness.grpersonIds
     *
     * @return the value of perbusiness.grpersonIds
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getGrpersonids() {
        return grpersonids;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perbusiness.grpersonIds
     *
     * @param grpersonids the value for perbusiness.grpersonIds
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setGrpersonids(String grpersonids) {
        this.grpersonids = grpersonids == null ? null : grpersonids.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perbusiness.grperbuTime
     *
     * @return the value of perbusiness.grperbuTime
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Date getGrperbutime() {
        return grperbutime;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perbusiness.grperbuTime
     *
     * @param grperbutime the value for perbusiness.grperbuTime
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setGrperbutime(Date grperbutime) {
        this.grperbutime = grperbutime;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perbusiness.grperbuType
     *
     * @return the value of perbusiness.grperbuType
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getGrperbutype() {
        return grperbutype;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perbusiness.grperbuType
     *
     * @param grperbutype the value for perbusiness.grperbuType
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setGrperbutype(String grperbutype) {
        this.grperbutype = grperbutype == null ? null : grperbutype.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perbusiness.perbuLimit
     *
     * @return the value of perbusiness.perbuLimit
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getPerbulimit() {
        return perbulimit;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perbusiness.perbuLimit
     *
     * @param perbulimit the value for perbusiness.perbuLimit
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setPerbulimit(Integer perbulimit) {
        this.perbulimit = perbulimit;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perbusiness.retrievingMeans
     *
     * @return the value of perbusiness.retrievingMeans
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getRetrievingmeans() {
        return retrievingmeans;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perbusiness.retrievingMeans
     *
     * @param retrievingmeans the value for perbusiness.retrievingMeans
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setRetrievingmeans(String retrievingmeans) {
        this.retrievingmeans = retrievingmeans == null ? null : retrievingmeans.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perbusiness.grapprovalStatuss
     *
     * @return the value of perbusiness.grapprovalStatuss
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getGrapprovalstatuss() {
        return grapprovalstatuss;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perbusiness.grapprovalStatuss
     *
     * @param grapprovalstatuss the value for perbusiness.grapprovalStatuss
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setGrapprovalstatuss(String grapprovalstatuss) {
        this.grapprovalstatuss = grapprovalstatuss == null ? null : grapprovalstatuss.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perbusiness.SettlementStatus
     *
     * @return the value of perbusiness.SettlementStatus
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getSettlementstatus() {
        return settlementstatus;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perbusiness.SettlementStatus
     *
     * @param settlementstatus the value for perbusiness.SettlementStatus
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setSettlementstatus(String settlementstatus) {
        this.settlementstatus = settlementstatus == null ? null : settlementstatus.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perbusiness.strike
     *
     * @return the value of perbusiness.strike
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getStrike() {
        return strike;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perbusiness.strike
     *
     * @param strike the value for perbusiness.strike
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setStrike(String strike) {
        this.strike = strike == null ? null : strike.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perbusiness.unitAdvancep
     *
     * @return the value of perbusiness.unitAdvancep
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getUnitadvancep() {
        return unitadvancep;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perbusiness.unitAdvancep
     *
     * @param unitadvancep the value for perbusiness.unitAdvancep
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setUnitadvancep(Integer unitadvancep) {
        this.unitadvancep = unitadvancep;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perbusiness.personAdvancep
     *
     * @return the value of perbusiness.personAdvancep
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getPersonadvancep() {
        return personadvancep;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perbusiness.personAdvancep
     *
     * @param personadvancep the value for perbusiness.personAdvancep
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setPersonadvancep(Integer personadvancep) {
        this.personadvancep = personadvancep;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perbusiness.bglx
     *
     * @return the value of perbusiness.bglx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getBglx() {
        return bglx;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perbusiness.bglx
     *
     * @param bglx the value for perbusiness.bglx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setBglx(String bglx) {
        this.bglx = bglx == null ? null : bglx.trim();
    }
}