package com.entity;

import java.util.Date;

public class Returnpay {
<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returnpay.chbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer chbh;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returnpay.grzhbhs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer grzhbhs;

<<<<<<< HEAD
    private Integer grzhbh;

=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returnpay.grzhbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer grzhbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returnpay.chje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Long chje;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returnpay.shjn
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Long shjn;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returnpay.chsj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Date chsj;

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column returnpay.chbh
     *
     * @return the value of returnpay.chbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getChbh() {
        return chbh;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column returnpay.chbh
     *
     * @param chbh the value for returnpay.chbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setChbh(Integer chbh) {
        this.chbh = chbh;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column returnpay.grzhbhs
     *
     * @return the value of returnpay.grzhbhs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getGrzhbhs() {
        return grzhbhs;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column returnpay.grzhbhs
     *
     * @param grzhbhs the value for returnpay.grzhbhs
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setGrzhbhs(Integer grzhbhs) {
        this.grzhbhs = grzhbhs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column returnpay.grzhbh
     *
     * @return the value of returnpay.grzhbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getGrzhbh() {
        return grzhbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column returnpay.grzhbh
     *
     * @param grzhbh the value for returnpay.grzhbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setGrzhbh(Integer grzhbh) {
        this.grzhbh = grzhbh;
    }

<<<<<<< HEAD
    public Integer getGrzhbh() {
        return grzhbh;
    }

    public void setGrzhbh(Integer grzhbh) {
        this.grzhbh = grzhbh;
    }

=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column returnpay.chje
     *
     * @return the value of returnpay.chje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Long getChje() {
        return chje;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column returnpay.chje
     *
     * @param chje the value for returnpay.chje
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setChje(Long chje) {
        this.chje = chje;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column returnpay.shjn
     *
     * @return the value of returnpay.shjn
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Long getShjn() {
        return shjn;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column returnpay.shjn
     *
     * @param shjn the value for returnpay.shjn
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setShjn(Long shjn) {
        this.shjn = shjn;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column returnpay.chsj
     *
     * @return the value of returnpay.chsj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Date getChsj() {
        return chsj;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column returnpay.chsj
     *
     * @param chsj the value for returnpay.chsj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setChsj(Date chsj) {
        this.chsj = chsj;
    }
}