package com.entity;

public class Shzt {
<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shzt.shbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer shbh;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shzt.shxq
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String shxq;

<<<<<<< HEAD
    private String 驳回原因;
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shzt.bhyy
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private String bhyy;
>>>>>>> refs/remotes/origin/wangcc

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shzt.shbh
     *
     * @return the value of shzt.shbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getShbh() {
        return shbh;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shzt.shbh
     *
     * @param shbh the value for shzt.shbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setShbh(Integer shbh) {
        this.shbh = shbh;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shzt.shxq
     *
     * @return the value of shzt.shxq
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getShxq() {
        return shxq;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shzt.shxq
     *
     * @param shxq the value for shzt.shxq
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setShxq(String shxq) {
        this.shxq = shxq == null ? null : shxq.trim();
    }

<<<<<<< HEAD
    public String get驳回原因() {
        return 驳回原因;
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shzt.bhyy
     *
     * @return the value of shzt.bhyy
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public String getBhyy() {
        return bhyy;
>>>>>>> refs/remotes/origin/wangcc
    }

<<<<<<< HEAD
    public void set驳回原因(String 驳回原因) {
        this.驳回原因 = 驳回原因 == null ? null : 驳回原因.trim();
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shzt.bhyy
     *
     * @param bhyy the value for shzt.bhyy
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setBhyy(String bhyy) {
        this.bhyy = bhyy == null ? null : bhyy.trim();
>>>>>>> refs/remotes/origin/wangcc
    }
}