package com.entity;

public class Shzt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shzt.shbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer shbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shzt.shxq
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private String shxq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shzt.bhyy
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private String bhyy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shzt.shbh
     *
     * @return the value of shzt.shbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getShbh() {
        return shbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shzt.shbh
     *
     * @param shbh the value for shzt.shbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setShbh(Integer shbh) {
        this.shbh = shbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shzt.shxq
     *
     * @return the value of shzt.shxq
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public String getShxq() {
        return shxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shzt.shxq
     *
     * @param shxq the value for shzt.shxq
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setShxq(String shxq) {
        this.shxq = shxq == null ? null : shxq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shzt.bhyy
     *
     * @return the value of shzt.bhyy
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public String getBhyy() {
        return bhyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shzt.bhyy
     *
     * @param bhyy the value for shzt.bhyy
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setBhyy(String bhyy) {
        this.bhyy = bhyy == null ? null : bhyy.trim();
    }
}