package com.entity;

public class Sys_user_role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.id3
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer id3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.userId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.role_id
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.id3
     *
     * @return the value of sys_user_role.id3
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getId3() {
        return id3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.id3
     *
     * @param id3 the value for sys_user_role.id3
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setId3(Integer id3) {
        this.id3 = id3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.userId
     *
     * @return the value of sys_user_role.userId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.userId
     *
     * @param userid the value for sys_user_role.userId
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.role_id
     *
     * @return the value of sys_user_role.role_id
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.role_id
     *
     * @param roleId the value for sys_user_role.role_id
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}