package com.entity;

public class Unitsaccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitsaccount.UnitInfoAccount
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    private Integer unitinfoaccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitsaccount.UnitInfoId
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    private Integer unitinfoid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitsaccount.UnitsName
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    private String unitsname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitsaccount.UnitsDepositRatio
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    private String unitsdepositratio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitsaccount.UnitsIndividua
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    private String unitsindividua;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitsaccount.UnitsDeposite
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    private Integer unitsdeposite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitsaccount.UnitsArchive
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    private Integer unitsarchive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitsaccount.UnitsBalance
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    private Integer unitsbalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitsaccount.nitsCancelDate
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    private String nitscanceldate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitsaccount.UnitesCancelCause
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    private String unitescancelcause;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitsaccount.UnitesState
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    private String unitesstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitsaccount.UnitesPaiduntil
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    private String unitespaiduntil;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitsaccount.UnitesArrearsMoney
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    private String unitesarrearsmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitsaccount.UnitesArrearsMonths
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    private String unitesarrearsmonths;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitsaccount.Unitesdeposit
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    private String unitesdeposit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitsaccount.UnitesUsername
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    private String unitesusername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitsaccount.UnitesAccount
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    private String unitesaccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitsaccount.UnitesTrustee
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    private String unitestrustee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitsaccount.UnitesBankname
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    private String unitesbankname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitsaccount.UnitesAccounts
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    private String unitesaccounts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unitsaccount.UnitesPerson
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    private String unitesperson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitsaccount.UnitInfoAccount
     *
     * @return the value of unitsaccount.UnitInfoAccount
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public Integer getUnitinfoaccount() {
        return unitinfoaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitsaccount.UnitInfoAccount
     *
     * @param unitinfoaccount the value for unitsaccount.UnitInfoAccount
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public void setUnitinfoaccount(Integer unitinfoaccount) {
        this.unitinfoaccount = unitinfoaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitsaccount.UnitInfoId
     *
     * @return the value of unitsaccount.UnitInfoId
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public Integer getUnitinfoid() {
        return unitinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitsaccount.UnitInfoId
     *
     * @param unitinfoid the value for unitsaccount.UnitInfoId
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public void setUnitinfoid(Integer unitinfoid) {
        this.unitinfoid = unitinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitsaccount.UnitsName
     *
     * @return the value of unitsaccount.UnitsName
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public String getUnitsname() {
        return unitsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitsaccount.UnitsName
     *
     * @param unitsname the value for unitsaccount.UnitsName
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public void setUnitsname(String unitsname) {
        this.unitsname = unitsname == null ? null : unitsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitsaccount.UnitsDepositRatio
     *
     * @return the value of unitsaccount.UnitsDepositRatio
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public String getUnitsdepositratio() {
        return unitsdepositratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitsaccount.UnitsDepositRatio
     *
     * @param unitsdepositratio the value for unitsaccount.UnitsDepositRatio
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public void setUnitsdepositratio(String unitsdepositratio) {
        this.unitsdepositratio = unitsdepositratio == null ? null : unitsdepositratio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitsaccount.UnitsIndividua
     *
     * @return the value of unitsaccount.UnitsIndividua
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public String getUnitsindividua() {
        return unitsindividua;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitsaccount.UnitsIndividua
     *
     * @param unitsindividua the value for unitsaccount.UnitsIndividua
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public void setUnitsindividua(String unitsindividua) {
        this.unitsindividua = unitsindividua == null ? null : unitsindividua.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitsaccount.UnitsDeposite
     *
     * @return the value of unitsaccount.UnitsDeposite
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public Integer getUnitsdeposite() {
        return unitsdeposite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitsaccount.UnitsDeposite
     *
     * @param unitsdeposite the value for unitsaccount.UnitsDeposite
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public void setUnitsdeposite(Integer unitsdeposite) {
        this.unitsdeposite = unitsdeposite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitsaccount.UnitsArchive
     *
     * @return the value of unitsaccount.UnitsArchive
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public Integer getUnitsarchive() {
        return unitsarchive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitsaccount.UnitsArchive
     *
     * @param unitsarchive the value for unitsaccount.UnitsArchive
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public void setUnitsarchive(Integer unitsarchive) {
        this.unitsarchive = unitsarchive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitsaccount.UnitsBalance
     *
     * @return the value of unitsaccount.UnitsBalance
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public Integer getUnitsbalance() {
        return unitsbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitsaccount.UnitsBalance
     *
     * @param unitsbalance the value for unitsaccount.UnitsBalance
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public void setUnitsbalance(Integer unitsbalance) {
        this.unitsbalance = unitsbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitsaccount.nitsCancelDate
     *
     * @return the value of unitsaccount.nitsCancelDate
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public String getNitscanceldate() {
        return nitscanceldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitsaccount.nitsCancelDate
     *
     * @param nitscanceldate the value for unitsaccount.nitsCancelDate
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public void setNitscanceldate(String nitscanceldate) {
        this.nitscanceldate = nitscanceldate == null ? null : nitscanceldate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitsaccount.UnitesCancelCause
     *
     * @return the value of unitsaccount.UnitesCancelCause
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public String getUnitescancelcause() {
        return unitescancelcause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitsaccount.UnitesCancelCause
     *
     * @param unitescancelcause the value for unitsaccount.UnitesCancelCause
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public void setUnitescancelcause(String unitescancelcause) {
        this.unitescancelcause = unitescancelcause == null ? null : unitescancelcause.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitsaccount.UnitesState
     *
     * @return the value of unitsaccount.UnitesState
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public String getUnitesstate() {
        return unitesstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitsaccount.UnitesState
     *
     * @param unitesstate the value for unitsaccount.UnitesState
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public void setUnitesstate(String unitesstate) {
        this.unitesstate = unitesstate == null ? null : unitesstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitsaccount.UnitesPaiduntil
     *
     * @return the value of unitsaccount.UnitesPaiduntil
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public String getUnitespaiduntil() {
        return unitespaiduntil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitsaccount.UnitesPaiduntil
     *
     * @param unitespaiduntil the value for unitsaccount.UnitesPaiduntil
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public void setUnitespaiduntil(String unitespaiduntil) {
        this.unitespaiduntil = unitespaiduntil == null ? null : unitespaiduntil.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitsaccount.UnitesArrearsMoney
     *
     * @return the value of unitsaccount.UnitesArrearsMoney
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public String getUnitesarrearsmoney() {
        return unitesarrearsmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitsaccount.UnitesArrearsMoney
     *
     * @param unitesarrearsmoney the value for unitsaccount.UnitesArrearsMoney
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public void setUnitesarrearsmoney(String unitesarrearsmoney) {
        this.unitesarrearsmoney = unitesarrearsmoney == null ? null : unitesarrearsmoney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitsaccount.UnitesArrearsMonths
     *
     * @return the value of unitsaccount.UnitesArrearsMonths
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public String getUnitesarrearsmonths() {
        return unitesarrearsmonths;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitsaccount.UnitesArrearsMonths
     *
     * @param unitesarrearsmonths the value for unitsaccount.UnitesArrearsMonths
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public void setUnitesarrearsmonths(String unitesarrearsmonths) {
        this.unitesarrearsmonths = unitesarrearsmonths == null ? null : unitesarrearsmonths.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitsaccount.Unitesdeposit
     *
     * @return the value of unitsaccount.Unitesdeposit
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public String getUnitesdeposit() {
        return unitesdeposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitsaccount.Unitesdeposit
     *
     * @param unitesdeposit the value for unitsaccount.Unitesdeposit
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public void setUnitesdeposit(String unitesdeposit) {
        this.unitesdeposit = unitesdeposit == null ? null : unitesdeposit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitsaccount.UnitesUsername
     *
     * @return the value of unitsaccount.UnitesUsername
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public String getUnitesusername() {
        return unitesusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitsaccount.UnitesUsername
     *
     * @param unitesusername the value for unitsaccount.UnitesUsername
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public void setUnitesusername(String unitesusername) {
        this.unitesusername = unitesusername == null ? null : unitesusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitsaccount.UnitesAccount
     *
     * @return the value of unitsaccount.UnitesAccount
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public String getUnitesaccount() {
        return unitesaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitsaccount.UnitesAccount
     *
     * @param unitesaccount the value for unitsaccount.UnitesAccount
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public void setUnitesaccount(String unitesaccount) {
        this.unitesaccount = unitesaccount == null ? null : unitesaccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitsaccount.UnitesTrustee
     *
     * @return the value of unitsaccount.UnitesTrustee
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public String getUnitestrustee() {
        return unitestrustee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitsaccount.UnitesTrustee
     *
     * @param unitestrustee the value for unitsaccount.UnitesTrustee
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public void setUnitestrustee(String unitestrustee) {
        this.unitestrustee = unitestrustee == null ? null : unitestrustee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitsaccount.UnitesBankname
     *
     * @return the value of unitsaccount.UnitesBankname
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public String getUnitesbankname() {
        return unitesbankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitsaccount.UnitesBankname
     *
     * @param unitesbankname the value for unitsaccount.UnitesBankname
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public void setUnitesbankname(String unitesbankname) {
        this.unitesbankname = unitesbankname == null ? null : unitesbankname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitsaccount.UnitesAccounts
     *
     * @return the value of unitsaccount.UnitesAccounts
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public String getUnitesaccounts() {
        return unitesaccounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitsaccount.UnitesAccounts
     *
     * @param unitesaccounts the value for unitsaccount.UnitesAccounts
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public void setUnitesaccounts(String unitesaccounts) {
        this.unitesaccounts = unitesaccounts == null ? null : unitesaccounts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unitsaccount.UnitesPerson
     *
     * @return the value of unitsaccount.UnitesPerson
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public String getUnitesperson() {
        return unitesperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unitsaccount.UnitesPerson
     *
     * @param unitesperson the value for unitsaccount.UnitesPerson
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    public void setUnitesperson(String unitesperson) {
        this.unitesperson = unitesperson == null ? null : unitesperson.trim();
    }
}