package com.entity;

import java.util.Date;

public class Zhhbjl {
<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhhbjl.jlbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer jlbh;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhhbjl.grzhbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer grzhbh;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhhbjl.blgrzh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String blgrzh;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhhbjl.blgrywmxlsh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String blgrywmxlsh;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhhbjl.xhgrywmxlsh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String xhgrywmxlsh;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhhbjl.xhgrzh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String xhgrzh;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhhbjl.xhgrzhye
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Integer xhgrzhye;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhhbjl.xhgrdkzh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String xhgrdkzh;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhhbjl.xhgrdkye
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String xhgrdkye;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhhbjl.czr
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String czr;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhhbjl.czsj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private Date czsj;

<<<<<<< HEAD
=======
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhhbjl.tzzd1
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    private String tzzd1;

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhhbjl.jlbh
     *
     * @return the value of zhhbjl.jlbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getJlbh() {
        return jlbh;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhhbjl.jlbh
     *
     * @param jlbh the value for zhhbjl.jlbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setJlbh(Integer jlbh) {
        this.jlbh = jlbh;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhhbjl.grzhbh
     *
     * @return the value of zhhbjl.grzhbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getGrzhbh() {
        return grzhbh;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhhbjl.grzhbh
     *
     * @param grzhbh the value for zhhbjl.grzhbh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setGrzhbh(Integer grzhbh) {
        this.grzhbh = grzhbh;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhhbjl.blgrzh
     *
     * @return the value of zhhbjl.blgrzh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getBlgrzh() {
        return blgrzh;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhhbjl.blgrzh
     *
     * @param blgrzh the value for zhhbjl.blgrzh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setBlgrzh(String blgrzh) {
        this.blgrzh = blgrzh == null ? null : blgrzh.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhhbjl.blgrywmxlsh
     *
     * @return the value of zhhbjl.blgrywmxlsh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getBlgrywmxlsh() {
        return blgrywmxlsh;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhhbjl.blgrywmxlsh
     *
     * @param blgrywmxlsh the value for zhhbjl.blgrywmxlsh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setBlgrywmxlsh(String blgrywmxlsh) {
        this.blgrywmxlsh = blgrywmxlsh == null ? null : blgrywmxlsh.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhhbjl.xhgrywmxlsh
     *
     * @return the value of zhhbjl.xhgrywmxlsh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getXhgrywmxlsh() {
        return xhgrywmxlsh;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhhbjl.xhgrywmxlsh
     *
     * @param xhgrywmxlsh the value for zhhbjl.xhgrywmxlsh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setXhgrywmxlsh(String xhgrywmxlsh) {
        this.xhgrywmxlsh = xhgrywmxlsh == null ? null : xhgrywmxlsh.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhhbjl.xhgrzh
     *
     * @return the value of zhhbjl.xhgrzh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getXhgrzh() {
        return xhgrzh;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhhbjl.xhgrzh
     *
     * @param xhgrzh the value for zhhbjl.xhgrzh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setXhgrzh(String xhgrzh) {
        this.xhgrzh = xhgrzh == null ? null : xhgrzh.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhhbjl.xhgrzhye
     *
     * @return the value of zhhbjl.xhgrzhye
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Integer getXhgrzhye() {
        return xhgrzhye;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhhbjl.xhgrzhye
     *
     * @param xhgrzhye the value for zhhbjl.xhgrzhye
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setXhgrzhye(Integer xhgrzhye) {
        this.xhgrzhye = xhgrzhye;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhhbjl.xhgrdkzh
     *
     * @return the value of zhhbjl.xhgrdkzh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getXhgrdkzh() {
        return xhgrdkzh;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhhbjl.xhgrdkzh
     *
     * @param xhgrdkzh the value for zhhbjl.xhgrdkzh
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setXhgrdkzh(String xhgrdkzh) {
        this.xhgrdkzh = xhgrdkzh == null ? null : xhgrdkzh.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhhbjl.xhgrdkye
     *
     * @return the value of zhhbjl.xhgrdkye
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getXhgrdkye() {
        return xhgrdkye;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhhbjl.xhgrdkye
     *
     * @param xhgrdkye the value for zhhbjl.xhgrdkye
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setXhgrdkye(String xhgrdkye) {
        this.xhgrdkye = xhgrdkye == null ? null : xhgrdkye.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhhbjl.czr
     *
     * @return the value of zhhbjl.czr
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getCzr() {
        return czr;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhhbjl.czr
     *
     * @param czr the value for zhhbjl.czr
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setCzr(String czr) {
        this.czr = czr == null ? null : czr.trim();
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhhbjl.czsj
     *
     * @return the value of zhhbjl.czsj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public Date getCzsj() {
        return czsj;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhhbjl.czsj
     *
     * @param czsj the value for zhhbjl.czsj
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setCzsj(Date czsj) {
        this.czsj = czsj;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhhbjl.tzzd1
     *
     * @return the value of zhhbjl.tzzd1
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public String getTzzd1() {
        return tzzd1;
    }

<<<<<<< HEAD
=======
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhhbjl.tzzd1
     *
     * @param tzzd1 the value for zhhbjl.tzzd1
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
>>>>>>> refs/remotes/origin/wangcc
    public void setTzzd1(String tzzd1) {
        this.tzzd1 = tzzd1 == null ? null : tzzd1.trim();
    }
}