package com.dao;

import com.entity.Accumulation;

public interface AccumulationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accumulation
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int deleteByPrimaryKey(Integer accumulation);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accumulation
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int insert(Accumulation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accumulation
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int insertSelective(Accumulation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accumulation
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    Accumulation selectByPrimaryKey(Integer accumulation);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accumulation
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int updateByPrimaryKeySelective(Accumulation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accumulation
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int updateByPrimaryKey(Accumulation record);
}