package com.dao;

import java.util.List;
import java.util.Map;

import com.entity.Accumulation;

public interface AccumulationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accumulation
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int deleteByPrimaryKey(Integer accumulation);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accumulation
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int insert(Accumulation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accumulation
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int insertSelective(Accumulation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accumulation
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    Accumulation selectByPrimaryKey(Integer accumulation);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accumulation
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int updateByPrimaryKeySelective(Accumulation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accumulation
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int updateByPrimaryKey(Accumulation record);
  //查询所有
    public List<Map>queryAllcwh();
    //修改状态
    public void updatecwh(Accumulation accumulation);

}