package com.dao;

import com.entity.Bankdetails;

public interface BankdetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bankdetails
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int deleteByPrimaryKey(Integer bankdetailsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bankdetails
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int insert(Bankdetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bankdetails
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int insertSelective(Bankdetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bankdetails
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    Bankdetails selectByPrimaryKey(Integer bankdetailsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bankdetails
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int updateByPrimaryKeySelective(Bankdetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bankdetails
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int updateByPrimaryKey(Bankdetails record);
}