package com.dao;

import com.entity.Bjqcb;

public interface BjqcbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjqcb
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int deleteByPrimaryKey(Integer bjbh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjqcb
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int insert(Bjqcb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjqcb
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int insertSelective(Bjqcb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjqcb
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    Bjqcb selectByPrimaryKey(Integer bjbh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjqcb
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int updateByPrimaryKeySelective(Bjqcb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjqcb
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int updateByPrimaryKey(Bjqcb record);
}