package com.dao;

import com.entity.BkshzjbKey;

public interface BkshzjbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bkshzjb
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int deleteByPrimaryKey(BkshzjbKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bkshzjb
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int insert(BkshzjbKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bkshzjb
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int insertSelective(BkshzjbKey record);
}