package com.dao;

import com.entity.Branded;

public interface BrandedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branded
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int deleteByPrimaryKey(Integer lmkbh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branded
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int insert(Branded record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branded
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int insertSelective(Branded record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branded
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    Branded selectByPrimaryKey(Integer lmkbh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branded
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int updateByPrimaryKeySelective(Branded record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branded
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int updateByPrimaryKey(Branded record);
}