package com.dao;

import com.entity.Dyhtxx;

public interface DyhtxxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dyhtxx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
	
	public int Dyhtxxsave(Dyhtxx dt);
	
    int deleteByPrimaryKey(Integer dbhtbh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dyhtxx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int insert(Dyhtxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dyhtxx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int insertSelective(Dyhtxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dyhtxx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    Dyhtxx selectByPrimaryKey(Integer dbhtbh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dyhtxx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int updateByPrimaryKeySelective(Dyhtxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dyhtxx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int updateByPrimaryKey(Dyhtxx record);
}