package com.dao;

import com.entity.Fjlxb;

public interface FjlxbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fjlxb
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int deleteByPrimaryKey(Integer fubh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fjlxb
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int insert(Fjlxb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fjlxb
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int insertSelective(Fjlxb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fjlxb
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    Fjlxb selectByPrimaryKey(Integer fubh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fjlxb
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int updateByPrimaryKeySelective(Fjlxb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fjlxb
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int updateByPrimaryKey(Fjlxb record);
}