package com.dao;

import java.util.List;
import java.util.Map;

import org.junit.validator.PublicClassValidator;

import com.entity.Grzfbkzhxx;

public interface GrzfbkzhxxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grzfbkzhxx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
	//查询还款状态为0未还清
	public List<Map<String,Object>> Grzfquery();
	//查询所有还款状态为1
	public List<Map<String, Object>> Grzfquerytwo();
	//修改状态
	public int updatestatic(int dkbh);
	//根据id 查询
	public List<Map<String, Object>> queryGrzgId(int dkbh);
	
	//分页模糊查询
	public List<Map<String, Object>> findbygrzfbk(Map<String, Object> grzfbk);
	//查询表的所有数量
    public Integer findcount(Map<String, Object> grzfbk);
    
	public int updateGrzfb(Map<String, Object> map);/*动态修改*/
    int deleteByPrimaryKey(Integer dkbh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grzfbkzhxx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int insert(Grzfbkzhxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grzfbkzhxx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int insertSelective(Grzfbkzhxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grzfbkzhxx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    Grzfbkzhxx selectByPrimaryKey(Integer dkbh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grzfbkzhxx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int updateByPrimaryKeySelective(Grzfbkzhxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grzfbkzhxx
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int updateByPrimaryKey(Grzfbkzhxx record);
}