package com.dao;

import com.entity.Gslxb;

public interface GslxbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gslxb
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int deleteByPrimaryKey(Integer gslxbh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gslxb
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int insert(Gslxb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gslxb
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int insertSelective(Gslxb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gslxb
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    Gslxb selectByPrimaryKey(Integer gslxbh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gslxb
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int updateByPrimaryKeySelective(Gslxb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gslxb
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int updateByPrimaryKey(Gslxb record);
}