package com.dao;

import com.entity.Guaporation;

public interface GuaporationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guaporation
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int deleteByPrimaryKey(Integer dbgsbh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guaporation
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int insert(Guaporation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guaporation
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int insertSelective(Guaporation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guaporation
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    Guaporation selectByPrimaryKey(Integer dbgsbh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guaporation
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int updateByPrimaryKeySelective(Guaporation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guaporation
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int updateByPrimaryKey(Guaporation record);
}