package com.dao;

import com.entity.Individualpay;

public interface IndividualpayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table individualpay
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int deleteByPrimaryKey(Integer grzhbhs);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table individualpay
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int insert(Individualpay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table individualpay
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int insertSelective(Individualpay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table individualpay
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    Individualpay selectByPrimaryKey(Integer grzhbhs);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table individualpay
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int updateByPrimaryKeySelective(Individualpay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table individualpay
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int updateByPrimaryKey(Individualpay record);
}