package com.dao;

import com.entity.Lenderspou;

public interface LenderspouMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lenderspou
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int deleteByPrimaryKey(Integer pobh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lenderspou
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int insert(Lenderspou record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lenderspou
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int insertSelective(Lenderspou record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lenderspou
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    Lenderspou selectByPrimaryKey(Integer pobh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lenderspou
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int updateByPrimaryKeySelective(Lenderspou record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lenderspou
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int updateByPrimaryKey(Lenderspou record);
}