package com.dao;

import com.entity.Messagement;

public interface MessagementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagement
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int deleteByPrimaryKey(Integer messageid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagement
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int insert(Messagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagement
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int insertSelective(Messagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagement
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    Messagement selectByPrimaryKey(Integer messageid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagement
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int updateByPrimaryKeySelective(Messagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagement
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int updateByPrimaryKey(Messagement record);
}