package com.dao;

import com.entity.Overdue;

public interface OverdueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overdue
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int deleteByPrimaryKey(Integer yqdjbh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overdue
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int insert(Overdue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overdue
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int insertSelective(Overdue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overdue
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    Overdue selectByPrimaryKey(Integer yqdjbh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overdue
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int updateByPrimaryKeySelective(Overdue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overdue
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int updateByPrimaryKey(Overdue record);
}