package com.dao;

import com.entity.Perbusiness;

public interface PerbusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perbusiness
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int deleteByPrimaryKey(Integer perbuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perbusiness
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int insert(Perbusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perbusiness
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int insertSelective(Perbusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perbusiness
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    Perbusiness selectByPrimaryKey(Integer perbuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perbusiness
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int updateByPrimaryKeySelective(Perbusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perbusiness
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int updateByPrimaryKey(Perbusiness record);
}