package com.dao;

import java.util.List;
import java.util.Map;

import com.entity.Repayplan;

public interface RepayplanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayplan
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
	//¸ù¾Ýid²éÑ¯
		public List<Map<String, Object>> queryDyhtxx(int dkbh);

    int deleteByPrimaryKey(Integer jhbh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayplan
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int insert(Repayplan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayplan
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int insertSelective(Repayplan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayplan
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    Repayplan selectByPrimaryKey(Integer jhbh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayplan
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int updateByPrimaryKeySelective(Repayplan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repayplan
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int updateByPrimaryKey(Repayplan record);
}