package com.dao;

import java.util.List;
import java.util.Map;

import com.entity.Unitsaccount;

public interface UnitsaccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unitsaccount
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int deleteByPrimaryKey(Integer unitinfoaccount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unitsaccount
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int insert(Unitsaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unitsaccount
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int insertSelective(Unitsaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unitsaccount
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    Unitsaccount selectByPrimaryKey(Integer unitinfoaccount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unitsaccount
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int updateByPrimaryKeySelective(Unitsaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unitsaccount
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int updateByPrimaryKey(Unitsaccount record);
    //²éÑ¯ËùÓÐ
    public List<Map>queryAllcwh();
    public int savecwh(Unitsaccount g);
}