package com.dao;

import java.util.List;
import java.util.Map;

import com.entity.Unitinfo;

public interface UnitinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unitinfo
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int deleteByPrimaryKey(Integer unitinfoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unitinfo
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int insert(Unitinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unitinfo
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int insertSelective(Unitinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unitinfo
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    Unitinfo selectByPrimaryKey(Integer unitinfoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unitinfo
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int updateByPrimaryKeySelective(Unitinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unitinfo
     *
     * @mbg.generated Sun Oct 21 20:42:37 CST 2018
     */
    int updateByPrimaryKey(Unitinfo record);
    //查询所有
    public List<Map>queryAllcwh();
   //添加
    public int savecwh(Unitinfo u);
    //删除
    public int deletecwh(int UnitInfoId);
   //修改
    public int updateunitinfocwh(Unitinfo u);
    //根据id查询
    public List<Unitinfo> queryByUnitinfoIdcwh(int unitinfoid);
}