package com.dao;

import com.entity.Zhhbjl;

public interface ZhhbjlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhhbjl
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int deleteByPrimaryKey(Integer jlbh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhhbjl
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int insert(Zhhbjl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhhbjl
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int insertSelective(Zhhbjl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhhbjl
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    Zhhbjl selectByPrimaryKey(Integer jlbh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhhbjl
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int updateByPrimaryKeySelective(Zhhbjl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhhbjl
     *
     * @mbg.generated Wed Oct 31 09:19:01 CST 2018
     */
    int updateByPrimaryKey(Zhhbjl record);
}